### ISSUE TITLE
Feature request: Keyboard layout to be set in config file

### ISSUE THREAD

**Issue by hztirf** [mtytel/helm#10]
Hi,

first of all: You're doing a great job here - hours of fun! :)

As I'm travelling on a frequent basis, I've not always a MIDI-keyboard with me. So my laptop's keyboard is used as replacement on-the-go. 

My laptop is equipped with a German keyboard layout, basically "Z" and "Y" are switched: On a German layout G# is where "octave down" is on a US layout.

Feature request: Would it be possible to move the key assignments from "helm_computer_keyboard.cpp" to an external config file? 

Thanks in advance and keep going on.

Hannes

(I use the standalone version)

**Comment by mtytel** [comment]
I love when these requests come in :)
Sure thing I'll put this in, should be easy enough.

**Comment by mtytel** [comment]
Sorry about the loooong delay on this one. But I just added the keyboard layout to the configuration file.
Next build (v0.5.0) will create a config file on startup.
On GNU/Linux the config file is here: ~/.helm/Helm.config
On OSX the config file is here: ~/Library/Application Support/helm/Helm.config
On Windows the config file is here: C:\Documents and Settings\username\Application Data\helm\Helm.config

Then you can modify the "keyboard_layout" section in a text editor, and on the next startup will load the new keyboard layout.

If this works for you let me know :)

Eventually I might put something in the settings/about section when you click on the logo, but I'll need to collect a lot of layouts before I do that.

**Comment by hztirf** [comment]
Awesome - Thank you for your efforts, I'll test it in the next couple of days and report back.

**Comment by hztirf** [comment]
I have tested it on Windows 7 as stand-alone version and it works out-of-the-box. Thank you. :)

**Comment by mtytel** [comment]
Great news :D
