### ISSUE TITLE
Windows Build VS15: value.cpp needed include algorithm

### ISSUE THREAD

**Issue by OwenBrotherwood** [mtytel/helm#100]
Just did a build with fail, but added to value.cpp (mopo/src)
`#include <algorithm>`
for error with std::min 
I googled the error and added the include and it worked : I am no (cpp) programmer.

At some stage, I may get more serious and do a pull request but this is a little heads up for the vs15 sln
## 

Thank you for the great program: I help kids in my freetime to play with music/coding/fun and I hope to use Helm for some project frontend for some hw that will probably be Raspberry Pi.
Then the kids can make a piece of hw and say they did it themselves without having to go and buy plastic at the local music store.

**Comment by mtytel** [comment]
Ah yea. I made this change but forgot to push it upstream. Thanks.
