### ISSUE TITLE
Step Sequencer Stops Working

### ISSUE THREAD

**Issue by ssj71** [mtytel/helm#103]
Using Helm in ardour 5.0 something (built from git) on ubuntu 15.10 the step sequencer tends to mysteriously stop working. Looking at the animation on the transpose dial that the seq was modulating it looks like it somehow got a huge negative offset added to it (the green part was pegged to the bottom). Also the sound was really low like it was transposed down several octaves. In the KVR OSC thread there are a few other people commenting about the step seq causing crashes (I'm not sure which platform).  see http://www.kvraudio.com/forum/viewtopic.php?p=6540528#p6540528

I've attached my patch that was exibiting this issue. I tried deleting the helm instance and reloading the patch, but no luck. Once I closed ardour and reloaded the project it went back to normal. Once it was working again I bounced it and disabled the track, but I figured I ought to report the problem.
[Arpthing.helm.zip](https://github.com/mtytel/helm/files/439611/Arpthing.helm.zip)

**Comment by mtytel** [comment]
Back to working on Helm :D 
I've narrowed down and fixed one specific problem with the step sequencer that could cause a crash/infinite value.
Going to keep this open because I'm not quite sure this issues has the same cause.

**Comment by ssj71** [comment]
> Back to working on Helm :D
\o/
I'd noticed activity had dropped. Great to hear some progress is being made! Thanks!

**Comment by mtytel** [comment]
Yeah I was working on contract.. but that's finished up so back to Helm!

**Comment by mtytel** [comment]
I'm preeeeety sure I fixed this. (Fix will come out in next version). We can reopen this if it still happens.
