### ISSUE TITLE
manpage issue

### ISSUE THREAD

**Issue by trebmuh** [mtytel/helm#106]
Hi and thanks for helm, really nice piece of synth!
I'm using a updated Debian Jessie system with helm 0.8.6 .
The manpage say that `helm -h` or `helm --help` are supposed to show up a little help. It doesn't work. Instead of showing it, it launches helm.
Please note that the `helm -v` and `helm --version` commands are working as expected.

Hope that helps,
Olivier

**Comment by mtytel** [comment]
All fixed! It'll be out in the next version.

**Comment by trebmuh** [comment]
Thank you.
