### ISSUE TITLE
Win x64: Access to Helm_64 presets fails

### ISSUE THREAD

**Issue by hztirf** [mtytel/helm#11]
On Windows x64 Helm_64 looks at the "Program Files (x86)" (folder for 32-bit program files) while being installed by default in "Program Files" (folder for 64-bit program files).

As a workaround I've copied the presets to "Program Files (x86)\Helm\Patches" as well.

(I use the standalone-version)

**Comment by mtytel** [comment]
Ah yea.. there reason is because the 64 bit windows build is actually 32 bit! Yikes :/
This is really high up on my to do. Will be fixed next release.

**Comment by mtytel** [comment]
Fixed the windows 64 bit build. There's still an issue finding the patches if you move where the standalone executable is stored, but using the default works now. Will fix this other issue in the next release.
