### ISSUE TITLE
"Out of sight" in Live 9.4

### ISSUE THREAD

**Issue by n2dawoods** [mtytel/helm#111]
Currently Helm VST is installed in `C:\Users\Dean\Documents\Ableton\My Plugins` 
and the standalone in `C:\Program Files\Helm`  

Currently run Windows 7 Ultimate 32 Bit.

**Comment by mtytel** [comment]
Hey I know this was forever ago but I wasn't working on Helm at the time.
Do you mean you can't load Helm in Live 9.4?
You installed the 32 bit plugin correct?

**Comment by mtytel** [comment]
I've fixed a couple issues relating to this but if it comes up again in the next release (0.9) we can reopen this.
