### ISSUE TITLE
Audio Glitching Without Fixed Buffers

### ISSUE THREAD

**Issue by czchmate** [mtytel/helm#112]
I just want to report that when I export projects that use Helm 0.8.6 to WAV in FL Studio I experience digital artifacts/buzzing/glitching. The only workaround that I've found for this is to select the Fixed Size Audio Buffers troubleshooting option in the VST container's configuration options.

It would be nice if Helm were able to take advantage of variable size audio buffers like most every other plug-in that I use. If this is impossible due to coding restrictions, then it would be nice to have a note in the documentation about DAWs needing to specify fixed size audio buffers in order for the VST to render properly.

As a side note, this error does not happen when playing back the project normally. It only occurs in the exported, mixed-down audio.

**Comment by mtytel** [comment]
Alright I had fixed some buffer problems in the past. I just tested this on the development branch and it's working. Fixed buffer size disabled, exported to WAV, OGG, MP3 with different resample settings.

If when I release the next version 0.9.* and this is still an issue, we can reopen this.
