### ISSUE TITLE
Clicking When Envelope Release Set to 0

### ISSUE THREAD

**Issue by czchmate** [mtytel/helm#113]
There is a distinct click/pop on note off when the Amp Envelope or Filter Envelope are set to their lowest setting. I would recommend having a very small number set as the release "zero-value" instead of actual zero. It would most likely avoid this.

**Comment by mtytel** [comment]
A lot of people use the popping in sound design. Especially in percussive sounds.
So going to leave it the way it is for now. If you set it to a really low value it should give you what you want.

**Comment by unfa** [comment]
I agree, I sometimes want to have these clicks, so I'd prefer things to stay this way.

By default the Amplitude Ebvelope has a non-zero Attack and Release, so it produces no clicks.

I turn the attack to 0 for drum sounds or sharp bass synths or othet, sometimes for an 8-bit like patch I'd go for both Attack and Release at zero to get that cheap, clicky sound.
