### ISSUE TITLE
Using helm in LMMS

### ISSUE THREAD

**Issue by lukeoftheaura** [mtytel/helm#114]
Hi,
Is it possible to use helm inside LMMS?

Thanks

**Comment by BiRD4** [comment]
Yes! Although, it does have a few quite important bugs (#95, #96 #97). It can be done if you don't want to load or save presets or modify any of your Helm synths in the file after you have closed and reopened the file.

Just install Helm as usual, if you haven't already done so, and the .dll files (if you are using Windows) should be in C:\Program Files\Steinberg\VstPlugins (or C:\Program Files (x86)\Steinberg\VstPlugins, depending, I think) for use in VeSTige.

Hope that helped!

**Comment by mtytel** [comment]
Closing because this isn't a bug.

**Comment by RichardJECooke** [comment]
Hi. I'm trying Helm for the first time on Linux and want to try it in LMMS.  

But where does Helm install to in Ubuntu?  I don't know how to drag the .dll file into LMMS to use it as an instrument.

**Comment by RichardJECooke** [comment]
Ah, the LMMS FAQ says I must open the Vestige instrument, then load in the my VST's .dll file.

But the Helm FAQ says it installs a .so file on Linux, not a .dll. Where do I find the .dll?

**Comment by karmux** [comment]
@RichardJECooke I installed Windows version with Wine and using installed .dll with VeSTige.

**Comment by RichardJECooke** [comment]
Thanks @karmux. Wine didn't work for me (pages of errors) but PlayOnLinux managed to install the 32 bit .msi file. 

I then opened the .dll in Vestige from /home/PlayOnLinux's virtual drives/v/drive_c/Program Files/Steinberg/VstPlugins.

It sounds, but the GUI is a blank screen. Did you encounter this error and find a way to get it to work?

![screenshot from 2018-01-09 11-49-41](https://user-images.githubusercontent.com/5468805/34699885-a3da34d4-f52b-11e7-9cbc-9b8a1934592e.png)

**Comment by karmux** [comment]
@RichardJECooke Installed 32-bit Helm using `wine msiexec /i xyz.msi` command. Try LMMS 1.2.0-RC5  that has lots of VST fixes compared to 1.1.3. There is also a [portable](https://github.com/LMMS/lmms/releases/download/v1.2.0-rc5/lmms-1.2.0-rc5-linux-x86_64.AppImage) version of it that requires no install.
