### ISSUE TITLE
Retrigger Mode for Step Sequencer Does Not Work in LMMS

### ISSUE THREAD

**Issue by BiRD4** [mtytel/helm#115]
If the step sequencer is set to retrigger, it still acts as though it is set to free.

I was using Windows 8.1 64-bit and LMMS version 1.1.3. I used VeSTige to open Helm.

**Comment by mtytel** [comment]
Just tested this and it's working for me.
I fixed a bug where the arp wouldn't retrigger anything, was that the issue?
Might have also gotten fixed somewhere else..

Fix will come out in the next version.

**Comment by BiRD4** [comment]
Did you reproduce using LMMS?
