### ISSUE TITLE
Feature Request - More Filters

### ISSUE THREAD

**Issue by BiRD4** [mtytel/helm#116]
I was recently doing some sound design thingies when I discovered that Massive has two filters. (Or, rather, I realized that this fact was actually quite important - more important than I had believed it to be before then.) I had already known for some time that Serum has lots of filter options. I thought that this feature was very useful, and so I wanted to suggest that multiple filters be added to Helm.

https://cloud.githubusercontent.com/assets/20910668/21546276/c1d22986-cdab-11e6-9ab8-48f2d7409490.png

Sorry if the picture looks a bit sloppy. :/

I suggest that the user is given the option to add as many "sub filters" as they need, that an "overall filter" is added so that the user can see what all of the sub filters add up to, and that the sub filters' influence on the overall filter can be modulated. It would also be absolutely incredible if sub filters could multiply, subtract, and divide each other instead of only being able to add to each other. To do this properly, the adding/subtracting/multiplying/dividing should be done in order from the first sub filter to the last filter. The order of the sub filters should be able to be changed very easily.

**Comment by mtytel** [comment]
Hmmmmmm interesting.
I was thinking of doing something like this. My plan was to have two filters with multiple routings so you could run them in series, in parallel or split them in stereo. 
I'll think about this sub filter stuff..

**Comment by BiRD4** [comment]
Sounds like you have some good ideas about the way you want the filters going. The only concern that I have about my ideas is the CPU usage.

**Comment by quesada** [comment]
+1 from me. A 24db filter would be good too. There might be some FOSS filter designs out there that could be reused straight?

**Comment by BiRD4** [comment]
LB302 has a 24db filter.

**Comment by mtytel** [comment]
Hmmm I like their 12db, but the 24db sounds a bit weird with high resonance.
I'm currently playing around with some 24db implementations. Trying to get them to drive/distort in a nice way.

**Comment by BiRD4** [comment]
I guess one of these filters could be added along with changing how the saturation works, in that case. They would probably go nicely together.

**Comment by mtytel** [comment]
Added a 24dB trigger for low-pass, high-pass and band-pass filters in the development branch.
I also inserted some non-linearities into the filters so you can drive the filter with the saturation.
