### ISSUE TITLE
Feature Request - More Control Over Oscillators and Modulation

### ISSUE THREAD

**Issue by BiRD4** [mtytel/helm#117]
ZynAddSubFX has a well made interface for creating oscillators in ADsynth, and it would be very nice to see a similar interface in Helm. In ZynAddSubFX, after a waveform type is chosen, filters and waveshaping options can be chosen. In addition to these options, the amplitude of each of the waveform's harmonics can be increased or decreased. What I consider to be most important of these, however, is the option to increase or decrease the amplitude of each of the waveform's harmonics. This allows for many more types of oscillators to be used in Helm.

Also, currently, there are only three LFOs, three envelopes (one of which is the volume envelope), and one step sequencer in Helm. I think that having more of each of these would significantly improve Helm's modulation capabilities, especially when using the proposed filter changes in #116. One way to approach the issue of finding space for the LFOs, envelopes, and step sequencers is to use a design like Serum's, in which sections of the window are dedicated to LFOs or envelopes, and they have tabs for switching between different LFOs or envelopes.

Another way to approach this is to have a modulation tab in Helm, in which any LFOs, envelopes, and step sequencers that are not already on the main tab are kept (aside from Mono LFO 2, which can be removed from the main tab). Ideally, an infinite number of LFOs, envelopes, and step sequencers could be added to the modulation tab in Helm, like FX channels in LMMS.

Here is a picture showing this idea with the huge button, labelled, "modulation." This button would switch to the modulation tab. The picture also shows buttons for changing the oscillators and the harmonics of the waveforms.
https://cloud.githubusercontent.com/assets/20910668/21548272/5f963cae-cdb9-11e6-97dc-2f270ebb6eaa.png

The buttons below the oscillators are there for opening the giving the user the interface for changing the amplitude of each of the base waveform's harmonics. I only put the buttons below the oscillators in the picture, but in their actual implementation, they should be with the sub and LFOs, also. It should be noted that if the step sequencer, LFOs, and the modulation envelope were moved from the main tab to the modulation tab, there would be more room for:

a) putting tab icons on the window (removing the mod envelope from the main tab and moving the arp, stutter, delay, formant, reverb, and volume sections down to take its place and then putting tabs where the arp was might work well)

b) future additions to the main tab

I do not suggest that the giant, inconvenient modulation button be kept on the main tab, but I suggest that, in its place, tabs are put at the top right corner of the window. (As stated in "a)")

**Comment by zediiiii** [comment]
I second this idea. Falcon VST has an interesting way of dealing with this - each LFO (or any kind of modulator) is a "snap-in" that is procedurally generated and placed in a list with an edit button that pops open the gui in it's own sub-window. Lists are an alternate to tabs, though both can work together in a powerful way as well.

**Comment by mtytel** [comment]
These are some awesome ideas. I won't be implementing them in Helm but I will probably do a lot of these in my next synth that's in the works.

Thanks!

**Comment by zediiiii** [comment]
Love your stuff @mtytel. Make sure to link it in various places so we can give you more money and use your stuff? =)

**Comment by mtytel** [comment]
Yeah when there's a beta I'll make an announcement! Probably a year from now..
