### ISSUE TITLE
Importing presets does not work on MAC

### ISSUE THREAD

**Issue by Snaal** [mtytel/helm#119]
Hi!
I am trying to install the two "Helmium" presets packs found on KVR homepage. Works ok on PC. Does not work on MAC. I am on a MAC Prod 2010. Mavericks. 3.2 Ghz.  Error seems to lie within Helm and not the presets.

Anybody with the same experience?

**Comment by mtytel** [comment]
There's a new import/export feature coming up in the next version that will make this a lot easier. Packs will need to be reexported however..

**Comment by WoolibuddhaWobbler** [comment]
Hello... can anyone load new presets for Helm on a Mac AU yet ?... no matching files, locked to create a new one... real pity a beautiful little synth.
