### ISSUE TITLE
cant make vst

### ISSUE THREAD

**Issue by billyblackburn** [mtytel/helm#122]
~/Downloads/helm-master $ make vst
make -C builds/linux/VST CONFIG=Release DEBCXXFLAGS="" DEBLDFLAGS=""
make[1]: Entering directory '/home/tertl3/Downloads/helm-master/builds/linux/VST'
Compiling juce_VST_Wrapper.cpp
../../../JUCE/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:69:51: fatal error: public.sdk/source/vst2.x/audioeffectx.h: No such file or directory
 #include <public.sdk/source/vst2.x/audioeffectx.h>
                                                   ^
compilation terminated.
Makefile:781: recipe for target 'build/intermediate/Release/juce_VST_Wrapper_6cac13de.o' failed
make[1]: *** [build/intermediate/Release/juce_VST_Wrapper_6cac13de.o] Error 1
make[1]: Leaving directory '/home/tertl3/Downloads/helm-master/builds/linux/VST'
Makefile:41: recipe for target 'vst' failed
make: *** [vst] Error 2

**Comment by mtytel** [comment]
Have you downloaded the vst sdk? I'm legally not able to distribute it. 
You can get it from the steinberg website and the makefile includes it if it has this path: "~/srcs/VST3 SDK"

**Comment by billyblackburn** [comment]
i did that and still getting the same error

tertl3@tertl3host ~/srcs $ ls
VST3 SDK



tertl3@tertl3host ~/Downloads/helm-master $ sudo make vst
make -C builds/linux/VST CONFIG=Release DEBCXXFLAGS="" DEBLDFLAGS=""
make[1]: Entering directory '/home/tertl3/Downloads/helm-master/builds/linux/VST'
Compiling juce_VST_Wrapper.cpp
../../../JUCE/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:69:51: fatal error: public.sdk/source/vst2.x/audioeffectx.h: No such file or directory
 #include <public.sdk/source/vst2.x/audioeffectx.h>
                                                   ^
compilation terminated.
Makefile:781: recipe for target 'build/intermediate/Release/juce_VST_Wrapper_6cac13de.o' failed
make[1]: *** [build/intermediate/Release/juce_VST_Wrapper_6cac13de.o] Error 1
make[1]: Leaving directory '/home/tertl3/Downloads/helm-master/builds/linux/VST'
Makefile:41: recipe for target 'vst' failed
make: *** [vst] Error 2

**Comment by billyblackburn** [comment]
its not a big deal since the lv2 is working, i just wanted to let you know about it

**Comment by napcode** [comment]
You probably don't want to build as root. It's not the best idea to begin with and it might set HOME to something you don't want. Check the path of the SDK again and try to build as user tertl3.

**Comment by billyblackburn** [comment]
yes you are correct, i removed the folder completely and recloned and didnt use sudo and it worked.  thank you
