### ISSUE TITLE
(Semi-)Modularity?

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#127]
I really like the design of Helm and the possibilities that it's flexible modulation gives.

Something I lack however is the ability to shuffle the modules around to use the modules we have in a different order. Sometimes I'd like to filter my sound after the saturation. Sometimes I'd like to mix back some of the filtered signal to the non-filtered one.

Sometimes I'd like to mix noise source after the filter, or sometimes I'd like to make my sub oscillator bypass the filter completely. Or make the Formant filter affect only the noise source. Or put the stutter before the amplitude envelope and filter.

I see some similarities between Helm and NI Massive - the control modulation system behaves and looks similar, and that's a great feature.

I don't know how Helm is designed internally. Would it be possible to add a "Routing switch matrix" like a "backplate" where one could reconfigure the internal signal routing?

I think introducing semi-modularity into Helm's design is an idea that could make Helm 2.0 - a major difference, bringing an abundance of new sounds possible.

I image it could work like this:

1. The main view stays what it is - the usual Helm controls.
2. There is a "Routing" button that makes all the frames display only input and output "wires" showing the current connections. A little bit like the back of the rack in Reason, or the back of the modular synth in Caustic 3. The user could pull and plug the wires to alter connections, re-route modules as they like.

The amount of change the users can do in the routing is something that needs to be thought through. How much freedom is going to benefit the users, and how much will make it a complete mess that no one can touch not to break it completely? I don't know.

Do you think this is even worth talking about?

**Comment by mtytel** [comment]
This sounds appealing, but if I ended up doing this it would an entirely separate project.
A goal of Helm is ease of use and this is definitely a power user feature. So even though it's cool I'm going punt on it for Helm. Thanks for requesting though!

**Comment by unfa** [comment]
I see, no problem, thanks for sharing your vision :)
