### ISSUE TITLE
Stereo width and panning

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#128]
One problem with Helm is it always produces a monophonic sound. The only way to add some width is by using the reverb, but that is not very flexible.

I'd expect that engaging unison for oscillators will also pan the voices left and right to produce a wide stereo image, but no - it's all in the dead center. It'd be great if one could play around with stereo width and panning controls to make use of  the L and R channels we have.

Ideas for improvement:

1. Pan/width controls for sources in the Mixer (Ardour Style?)
2. Or Width controls for Unison in oscillators 1 & 2 and Pan controls in the mixer.
3. Noise generator stereo width control.
4. L/R time difference for delay effect.
5. L/R pitch difference fro Feedback.

**Comment by mtytel** [comment]
Yeah... A lot of people have requested this.
closing because of duplicate, added your ideas: #40
