### ISSUE TITLE
Make saturation auto-auttenuate to keep the loudness sane

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#129]
When I use saturation, I always need to reduce the main volume beforehand, to avoid blowing my eardrums.

It'd be really nice if Saturation could automatically attenuate the sound wit ha post-gain as much as the pre-gain is turned up to try keeping a relatively constant level, and only change the character of the sound. It might be an optional thing, but I'd recommend do turn it on by default.

Also: dropping the saturation pre-gain below 0 dB (to attenuate without distorting) never proved useful in my workflow, do you guys use that?

**Comment by mtytel** [comment]
Well.. the saturation control kind of sucks and doesn't really do what it says.
It actually is just a gain control (ssshhhhh). Later on it's distorted if it's close to clipping.

I really should just rework what the saturation knob does.

**Comment by mtytel** [comment]
ok this sounds way better now that the filter saturation works. It's "auto attenuated" when you get close to saturation levels of the filter.

Will be out in the next version.
