### ISSUE TITLE
Freezes in Cubase 8.0.10 64bit, Windows 8.1

### ISSUE THREAD

**Issue by ntsarb** [mtytel/helm#13]
Hi,

When using Helm 64bit in Cubase 8.0.10 64bit, on Windows 8.1 Pro, if I make a few changes (play with)  the "A" attribute of the Amplitude Envelope, it often freezes the VST plugin and the whole of Cubase. I then have to End Task on Cubase.

Regards,
Nikos

**Comment by mtytel** [comment]
Humm.. So there's no crash, just hanging? Does the sound stop when it hangs or is it just the graphics?

Going to be hard to debug since I don't have Cubase. I probably should get a version of every DAW but that's a lot of moula for something I'm releasing for free. Maybe I can get an NFR if I get in contact with the some people from Steinberg and other companies.

**Comment by ntsarb** [comment]
It is the UI that freezes. While frozen, I can still hear what I plan on
the MIDI keyboard. While frozen, the application can't be minimized or
closed. Can't switch between other apps and Cubase either. The UI is not
responding.

**Comment by mtytel** [comment]
Sorry it took me a while to come back to this. Were you twiddling the attack through the GUI or through a MIDI interface?

**Comment by ntsarb** [comment]
Through the GUI.

Also, it freezes in Cubase 8.0.20 on macbook pro (latest OS x).

**Comment by mtytel** [comment]
Sorry I've been quiet on this one.
I fixed quite a few things that would cause hangs/crashes in the latest version (0.4.1) up on tytel.org/helm

Unfortunately I don't have Cubase so can't verify any of those fixes. If you haven't forgotten about me already, could you test out the newest build and let me know what you think? Thanks!

**Comment by ntsarb** [comment]
I can no longer reproduce those UI freezes, so I think you've nailed it down. Well done!

**Comment by mtytel** [comment]
Awesome! Thanks for testing it :)
