### ISSUE TITLE
Formant filter dry/wet and/or Q control?

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#130]
I wish I could fade the formant in and out with envelopes or LFOs.
A dry/wet control would be great!

**Comment by mtytel** [comment]
Hmm... Yea i think you're right!

**Comment by unfa** [comment]
After playing with ZynAddSubFX formant filter ( https://www.youtube.com/watch?v=Y93Jh1UIpys ) I think that a Q (or resonance) control could also be very nice. Maybe even better than dry/wet - as it'd gently make the peaks wider and less audible.

**Comment by mtytel** [comment]
I've got both a dry/wet mix and a q control in my next synth's formant filter. 
Won't be implementing in Helm though.

Thanks!
