### ISSUE TITLE
Setting LFO resting amplitude to zero is near impossible

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#132]
I discovered it's very difficult (feels impossible) to set the LFO's amplitude to zero.

I tried that to make the Modulation Wheel make the LFO depth non-zero to engage virato, but with mod wheel at 0% I want my LFO to have amplitude of 0 - it turns out that's very difficult.

You can see what I mean in this video:

https://youtu.be/qWLjHqJX6aw?t=1h9m13s

I wish there was a tiny bit of snapping in the middle or a way to type in numeric values by hand.

**Comment by mtytel** [comment]
Yes I've noticed this.. Maybe a magnet to zero would be good.

**Comment by mtytel** [comment]
Added a snap to zero for lfo amplitude and step sequencer.
Will be out in the next version.
