### ISSUE TITLE
Impossible to only install LV2 or standalone

### ISSUE THREAD

**Issue by simonvanderveldt** [mtytel/helm#137]
First of all thanks for the awesome synth! Really like it, both the sounds it can generate as well as the well thought through and good looking UI!

We're working at packaging Helm for gentoo (see https://github.com/gentoo-audio/audio-overlay/issues/16) and I ran into the following.
One of the important things we strive to do for gentoo is give the user choice what to build and install. Currently one can choose which targets to `make`: `standalone`, `lv2` and `vst`, but [`make install` always triggers `all`](https://github.com/mtytel/helm/blob/d5ed6d2b02399f4d8c6cebacf4882f4a6e0c64fa/Makefile#L48), which includes both `lv2` and `standalone`.

Now, there's already a [`install_vst`](https://github.com/mtytel/helm/blob/d5ed6d2b02399f4d8c6cebacf4882f4a6e0c64fa/Makefile#L58) target, I can create a PR to add `install_lv2` and `install_standalone`.
Would you be OK with this? And do you have any feedback or suggestions how you'd like it to work before I create a PR?

**Comment by mtytel** [comment]
How's this?
https://github.com/mtytel/helm/commit/23af45f4fce36d4921e1d4ff8388c60956c51684

**Comment by simonvanderveldt** [comment]
@mtytel Well, that's awesome! ;) And a lot quicker than me whipping up a PR :P
Thanks!

Since the first target (`all`) now builds everything [`install`](https://github.com/mtytel/helm/blob/23af45f4fce36d4921e1d4ff8388c60956c51684/Makefile#L71) should probably also install everything?

And you might want to update the [readme](https://github.com/mtytel/helm/blob/master/README.md#building) to match these changes?

**Comment by mtytel** [comment]
Good catch. I was keeping install_vst out of it for a license reason but it looks like I can build with the GPL version of the VST SDK so I've included it now.
I've also included the VST SDK in the source (since it's GPL now) so you don't have to download it separately anymore.

Updated README too.

**Comment by simonvanderveldt** [comment]
@mtytel Looks good, thanks for the quick fixes!
I'll run some builds this weekend, if I run into anything strange I'll let you know. Looking at the code/changes it should work fine though :)
