### ISSUE TITLE
Locked Note When Changing Tempo in LMMS

### ISSUE THREAD

**Issue by BiRD4** [mtytel/helm#138]
When I play a note while changing the tempo of a song, the note I played doesn't end until I have played it again. This might be an issue with LMMS, but I'm putting it here first just in case.

Using Windows 8.1 64-bit and LMMS version 1.2.0-rc2. I used VeSTige to open Helm.

**Comment by mtytel** [comment]
Were you using MIDI input or the visual keyboard input?

**Comment by BiRD4** [comment]
I only used MIDI input before, I can't reproduce with the visual keyboard, but I can reproduce it with the keyboard in the VeSTige window. I can't reproduce with ZynAddSubFX, so it's probably a problem with LMMS and VeStige.

**Comment by mtytel** [comment]
Cool thanks for looking into it.
