### ISSUE TITLE
Segfault on linux, standalone

### ISSUE THREAD

**Issue by kjyv** [mtytel/helm#139]
The segfault mentioned in a comment to #75 (observed on armv8) seems to not be related to X but happens when line 255 is reached in helm_module.cpp.
output_map sub_readouts = sub_module->getPolyModulations();
I don't have a proper debugging environment set up and with pure gdb, I'm not really able to see whats happening after.

**Comment by mtytel** [comment]
Does this happens regularly on startup?

**Comment by kjyv** [comment]
Yep, every time. I need to correct myself a bit, there is another segfault when starting without X running at juce_gui_basics/native/juce_linux_Windowing.cpp:927 calling XQueryExtension.

**Comment by kjyv** [comment]
This was actually on master, development branch now correctly gives "Failed to connect to the X Server." (which is however also printed when running with --headless).
It still segfaults when started under X, now on line 368 of helm_module.cpp.

**Comment by mtytel** [comment]
Fixed in develop.

**Comment by mtytel** [comment]
Thanks for the help!
