### ISSUE TITLE
Feature request: JACK client support for standalone Linux version

### ISSUE THREAD

**Issue by SpotlightKid** [mtytel/helm#14]
The title says it all...

Maybe even add JACK support on OS X.

**Comment by mtytel** [comment]
For sure! I'll see what I can do.

**Comment by mtytel** [comment]
Just pushed a fix for this. Will look for JACK by default and will fall back on ALSA.
Also added a settings menu to change audio preferences.

**Comment by mtytel** [comment]
This fix will go in version 0.4.1

**Comment by trebmuh** [comment]
Sweet !

**Comment by magnetophon** [comment]
I'm packaged Helm for NixOS, but it doesn't seem to work with jack.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/helm/default.nix
