### ISSUE TITLE
Can't build VST on Linux Mint 18.1

### ISSUE THREAD

**Issue by HiFiWiFi** [mtytel/helm#146]
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
No package 'alsa' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Makefile:948: recipe for target 'check-pkg-config' failed
make: *** [check-pkg-config] Error 1

**Comment by mtytel** [comment]
Do you have all these packages installed?
mesa-common-dev, libasound2-dev, libfreetype6-dev, libx11-dev, libxrandr-dev, libxinerama-dev, libxcursor-dev, freeglut3-dev, libxcomposite-dev, libjack-dev, libcurl4-gnutls-dev

**Comment by mtytel** [comment]
libasound2-dev and libcurl4-gnutls-dev are probably what you need for this error.

**Comment by HiFiWiFi** [comment]
Thanks mate,
I'll try those out.
