### ISSUE TITLE
0.9.0 .deb package says a newer version is already installed

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#149]
I have Helm 0.8.6 installed. When I downloaded the 0.9.0 .deb package and opened it  in GDebi, it said that "a later version is already installed".

So I had to remove my current Helm installation and even then GDebi warns me that "a later version is available in a software channel".

If I ignore this and proceed - the new Helm is installed and working fine.

Is there a problem with the version numbering?

**Comment by BiRD4** [comment]
Just to document my experience in case it helps:
When I opened Helm 0.8.6, it told me that 0.9.0 was available, so I downloaded it. However, when it started installing, it wouldn't work, even after waiting for several minutes. To try to fix the problem, I made a new folder in Steinberg>VSTPlugins for the .dll files and put them in there instead, so it looked like this: Steinberg>VSTPlugins>Old Versions. After that, it worked after just a few seconds.

**Comment by hammerandtongs** [comment]
Can confirm this

`
dpkg: warning: downgrading helm from 2:0.8.6-1kxstudio2 to 0.9.0-1354-time~ubuntu14.04.1`

Also the debian metadata files don't appear to be in git?

**Comment by falkTX** [comment]
This is not a bug, but a feature (of kxstudio).
KXStudio packages take preference over outside sources.
So this is working as intended. I'm updating helm in KXStudio today.

**Comment by unfa** [comment]
Oh, I was very confused by this :D Thanks, @falkTX !
