### ISSUE TITLE
Allow more detune for unison and more voices

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#151]
I found the current maximum of 100 cents to be quite limiting.

I'd like to be able to go up to 1 oct of detune - for some sound design and effect. I'd love to automate that of use an envelope to get from 1200c detune to 50 for example.

With these extreme amounts of detune also more voices could be a nice idea.

What do you think?

**Comment by unfa** [comment]
I'm thinking that maybe the Unison Detune scale  should be weighted -  we generally need more precision for small values (close to 0) and less precision as the detune gets bigger.

Not sure how that would play with envelopes and LFOs though.

**Comment by BiRD4** [comment]
Could have an option to set logarithmic/linear on right click like in LMMS.

**Comment by mtytel** [comment]
Hmmm. Yeah should be simple enough. Just a UI change because the back end doesn't have a limit.

Also @unfa, did you create those hilarious mario/growl recordings on freesound.org?
A few students of mine found those and used it for this instrument/sampling project and I was dyyyiiiinnngg. SO funny.

**Comment by unfa** [comment]
@mtytel: yes! I didn't know they made such a journey :D

**Comment by noxarivis** [comment]
@unfa i love your youtube vids, keep it on ;)
sorry for the off topic

**Comment by mtytel** [comment]
I'm going to leave Helm's unison alone but I have some kickass unison features coming in the next synth. It's got lots of customization including the scale mentioned.
