### ISSUE TITLE
Master volume resets to 100% every time you select a patch in standalone mode

### ISSUE THREAD

**Issue by hammerandtongs** [mtytel/helm#155]
Expectation -

Setting volume persists  through a session and across patches.

Actual Result - 

Volume jumps back to 100% every time a patch is selected.

**Comment by baderbuddy** [comment]
It's actually not resetting to 100% every time, it's resetting to whatever volume that patch was saved with. That way you could save your own patches with variable volumes, maybe you want your pad to always be quieter than your lead, or to boost the volume of your bass to make up for the LPF.

**Comment by hammerandtongs** [comment]
Yah I think the issue is that the audio levels are really inconsistent as you browse patches.

I can see it being somewhat useful setting the volume per patch but in practice, if I had a "ignore individual patch volume level" toggle I'd use it and then set it in whatever mixer I was using.

**Comment by hammerandtongs** [comment]
I guess I'm being grumpy with the individual patch creators so I'll close this to keep noise down in the helm issues list.
