### ISSUE TITLE
Feature: add wavetable oscillator

### ISSUE THREAD

**Issue by kjyv** [mtytel/helm#156]
Possibly not an easy to implement feature but it would be nice to additionally have arbitrary waves for oscillators/LFOs. I guess something like libsamplerate or libresample could be used for the resampling.

**Comment by patjak** [comment]
+1 would be a nice feature

**Comment by unfa** [comment]
So you mean a way to load an arbitrary audio file to be used as a cycle for the oscillators?

**Comment by kjyv** [comment]
Yes

**Comment by mtytel** [comment]
Not going to implement this in Helm. This'll go in Helm's successor though (already in the works).

**Comment by amilajack** [comment]
> This'll go in Helm's successor though (already in the works).

Woah. Is that open source too?

**Comment by mtytel** [comment]
It will be.
It's going to be a more formal release than I did for Helm. I don't want people distributing it before it's ready.

**Comment by twheelmaker** [comment]
the ability to load wavs as a special 'oscillator' type would be amazing! look at how nanostudio's eden synth allows arbitrary wav files for an oscillator... not so much for custom oscillator shapes (which would still be nice), but as a poor man's single zone sampler. this special oscillator could have playback direction, independent speed, pitch and crossfaded loop point params. you'd get all the familiar mod and fx from the synth engine too... very curious about helm's successor (and if there will also be a unity asset for it).
