### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [mtytel/helm#16]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/mtytel/helm/blob/c6fe13fafd0545aa19bdd5173933c0e9d8413f1f/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](http://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by mtytel** [comment]
I've used autotools in the past. I wasn't sure how to use both autotools and the auto generated build system used by JUCE so right now I'm just calling that Makefile. I'll revisit this in a bit. Thanks for filing this :)

**Comment by elfring** [comment]
Do you use just [an other file format](http://www.juce.com/learn/introjucer "JUCE's project-management tool") as [your primary build specification](https://github.com/mtytel/helm/blob/9546447fa7f3c32d6709c6516305e5109e59f74b/helm.jucer#L1 "Build configuration")?

**Comment by mtytel** [comment]
I probably am not going to do this so am closing this issue.
