### ISSUE TITLE
Crossmodulation doesn't use actual waveforms?

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#162]
I've been playing with the X-mod function (FM modulation between oscillators 1 and 2).

I discovered that if I have only OSC1 audible in the mixer, and enable X-mod, changing the OSC2 waveform has no effect on the sound.

Does the X-mod only operate on sine waves tuned to approperiate pitches?
Is that intentional? Will it be updated to take the waveforms into account?

**Comment by piece-o-ham** [comment]
The manual says this:

> The oscillators are simplified to a sine wave before the modulation is applied.

So yes, that is intentional.

**Comment by mtytel** [comment]
Yeah it's intentional because the normal waveforms get a little to crazy and just don't sound good. If I were to put work into cross mod I'd probably just replace it with another feature.

**Comment by unfa** [comment]
Ok, I get it. Thank you!
