### ISSUE TITLE
helm on app store

### ISSUE THREAD

**Issue by Reaper10** [mtytel/helm#166]
It would be great to see helm on app store. 
Android app store
windows app store
apple app store

**Comment by Harald-Koschinski** [comment]
Why? 
Helm is not a Android-APP - so what should be in the Playstore?

**Comment by Reaper10** [comment]
I have a friend who all he has is a android phone. I would love it on android for my tablet so I can sound deign on the go.

**Comment by Harald-Koschinski** [comment]
It's great that helm is running on all Desktop Plattforms - including Linux - Many thanks to Matt for this.
I compiled it on Opensuse without any problems or "adjustments"- great.
Is there any synthesizer available on Desktop and Android/IOS?? I don't think so.
I believe It's good to have helm on the now supported platforms. More brings just more problems.

**Comment by mtytel** [comment]
It's easy to get working on Android, but it's hard to make it work well. It would take some real big changes to the UI to get it to a point where I'd be happy releasing it in the Play Store. Probably would just be a different project.
As for the Windows/Mac app store. It costs a fair amount of money for a PWYW product, so probably won't do that either :/

**Comment by joebowbeer** [comment]
Times have changed. A growing number of AUv3 instruments and effects now run on multiple platforms, from PC to iOS. Even some entire DAWs (e.g., Zenbeats and Cubasis) run across platforms. Apple’s recent release of Mac Catalyst makes it possible for iOS and macOS apps to share mostly the same native codebase.
