### ISSUE TITLE
Anti-Aliasing

### ISSUE THREAD

**Issue by RCJacH** [mtytel/helm#174]
Is there any plan for implementation of any kind of anti-aliasing in the future? Currently the raw saw wave gets really harsh without band-limiting or over-sampled filters.

**Comment by mtytel** [comment]
Do you just mean in the inital patch or while enabling a filter?
The raw waveforms are band limited so there shouldn't be any aliasing with them.
The filters have some non-linearities which will alias at high drive values and if you enable cross-modulation you'll also get aliasing.
I could definitely improve these two in the future.

**Comment by mtytel** [comment]
Hmmmm after looking at this, it seems that the band limiting kicks in at notes higher than middle C.
I'll probably leave this how it is and improve the band limiting in my next synth since it would require some oversampling/decimation.
