### ISSUE TITLE
Linux Active MIDI Inputs show writable rather than readable devices

### ISSUE THREAD

**Issue by warrenfalk** [mtytel/helm#176]
In linux, the Active MIDI Inputs box in the settings lists the available devices, but the devices that show are the devices that are writable devices.  So if you have a device which has separate input/output ports, Helm will show you only the writable ports which are useless.

You can confirm this by installing mididings on linux, opening up a python 2.7 prompt and typing the following:
```
>>> from mididings import *
>>> run(Transpose(3))
```

Then go to Helm and notice that there is probably an "in_1" port showing... but you want the "out_1" port which it doesn't show.

**Comment by mtytel** [comment]
Filed this in upstream JUCE: https://github.com/WeAreROLI/JUCE/pull/341

**Comment by jjalocha** [comment]
Hello, I'm sorry to comment on an issue that has been closed, but for me (Linux, ALSA, Helm v 0.9.0), this is still happening. I see writable ports instead of readable ones, which prevents me from setting up meaningful connections. Am I doing something wrong?
