### ISSUE TITLE
dependency: samplerate <-> ARP 

### ISSUE THREAD

**Issue by fred41** [mtytel/helm#182]
Hi,
playing around with this great synth, i found that if i change the sample rate (settings), the ARP speed changes too. I dont think this behavoir is really intendet?

**Comment by mtytel** [comment]
Ah! Thanks for the report.
Just pushed a fix.

**Comment by fred41** [comment]
... huh, that was fast and it works great :) 

btw: 
Thank you for this beautyful and great sounding synth.

**Comment by KroniK907** [comment]
Any chance someone could send/post a current vst build? having this issue and cant find a way around it. I could build it but I really dont want to spend 2 hours getting my linux VM updated and running to build it.
