### ISSUE TITLE
GPL... Must make source available if using the Unity Asset?

### ISSUE THREAD

**Issue by twheelmaker** [mtytel/helm#192]
Sorry if this is the wrong place... Assuming the Helm Audio Unity Asset is purchased and the asset is distributed in a real-time musical mobile app via the apple / google app store, does the GPL license require that my source code be published? Does using the GPL asset require my source to be GPL? Also, I see reference to the JUCE lib in this repo... is JUCE license also a part of the Unity Asset? Thanks!

**Comment by mtytel** [comment]
Hey. You can email me at matthewtytel@gmail.com for other questions. But I'll answer here.

The short answer is the Audio Helm Unity Assets are distributed on a different (Unity Asset) license, not the GPL. So you don't have any GPL requirements for something you make in Unity with those assets. 

The standalone editor and VST/AU/LV2 plugins that you get from tytel.org/helm are GPL licensed. So you can't distribute those pieces of software with a Unity app (Unity is not compatible with the GPL). You can however distribute any patches created with the standalone editor/plugins. You own the copyright to any sound or patch created with these apps so you can release them however you like (e.g. use them in your Unity app with the Audio Helm Assets).

Many people have asked about JUCE as well. The Audio Helm Unity Assets don't actually use the JUCE library at all so there is no requirement there either.

**Comment by mtytel** [comment]
To clarify, the plugins built in the Audio Helm Unity Assets are a modified version of this repo.

**Comment by twheelmaker** [comment]
Thanks for the quick clarification. It's difficult to preview Unity Assets so I was just looking at this repo for insight. While I have your ear, does the sampler component support loop points (cross-faded 'sustain') 
 and ADSR? Does the asset provide abstract MIDI interface I/O... ie; not just MIDI file I/O, but  real-time send/receive over a MIDI interface? Great job btw!

**Comment by mtytel** [comment]
Thanks!
The sampler is very basic. Mostly just variable sample playback speed and velocity tracking.
No MIDI I/O right now. I've been thinking about making one though (possibly as another asset that pairs nicely with Audio Helm).
