### ISSUE TITLE
Can't open *.helm files

### ISSUE THREAD

**Issue by daeavelwyn** [mtytel/helm#194]
I must be quite dumb, but I just can't figure how to open a *.helm file from the synth interface. I can easily open *.helmbank, but not an *.helm file...Some clarification in ths documentation could really help !

**Comment by mtytel** [comment]
Try ctrl-S or click the "Export" button instead.
Glad you like Helm!

**Comment by daeavelwyn** [comment]
so...Ctrl+o and ctrl+s doesn't work while helm is used as a vst plugin. I'm trying in Reaper native for linux (from landoleet.org). This isn't a Reaper issue as other plugins work very nice.

**Comment by 6-AND-9** [comment]
> andoleet.org

can confirm this.
