### ISSUE TITLE
Sometimes Helm seems to get "stuck" on a note

### ISSUE THREAD

**Issue by baderbuddy** [mtytel/helm#197]
I'll apologize up front for how vague this is. I'm using the Helm AU on Mac inside Reaper. It for the most part works great, but every now and then after it's been playing for a few minutes if I hit the stop button in Reaper there will still be some residual sounds coming out of Helm. The little line on the envelope is acting like a key is pressed in still, but the virtual keyboard shows none of the keys are pressed. And it just sounds for the most part like I've just left some key on the keyboard pressed in. It seems to happen fairly consistently if I have Reaper sound MIDI for about 2 minutes. Really short sessions (10-20 seconds) don't seem to cause this issue. Pausing in Reaper does stop the sounds.

**Comment by mtytel** [comment]
Haven't seen this myself. So the line in the envelope stays at the sustain level? Or does it stay active but go into release?

If the note is released (not stuck) I might have missed the stop all sounds message.
If the note is in sustain, something weird is going on..

**Comment by baderbuddy** [comment]
It stays at the sustain level, it for the most part acts like some note is still held, except reverb is still making sounds on one of my patches that has a sustain of 0.

This is really weird to me, but I was using Midi Monitor to look at the midi coming out of Reaper when it stops. It sends all notes off on every channel, then pitch wheel 0, then it looks like it sends "Hold Pedal" on every channel, then a stop message and song position, then it still did a few notes after that.

Does Helm have any debugging features or logging I could turn on? It is possible this is a Reaper issue, this is the only virtual instrument I've been using.

**Comment by baderbuddy** [comment]
Oh the hold pedal messages have a 0 after them, so that must be making sure that sustain is off.

**Comment by baderbuddy** [comment]
I'm still not 100% sure what's going on, but I'm starting to think this is an issue with Reaper not Helm. I just had the same thing happen with a different synth and since the last time I upgraded Reaper it hasn't been happening with Helm (at least as reliably).
