### ISSUE TITLE
Reverb feedback modulation kills audio

### ISSUE THREAD

**Issue by MacroMachines** [mtytel/helm#199]
Due to the unclipped ranges allowed for some of the modulation parameters, specifically the reverb feedback and damp, the reverb can end up feeding back internally and ending up with what I assume is an inf. or nan.  
Two possible resolutions for this: tanh soft clip internally in the reverb feedback path, or even hard clip if you want.. or even limit.  Also a dc offset filter can help. 
The other is rather simply clip the input parameter values after modulation, so their range is limited.
and yes I know, I am a nut, I like modulating everything.. I make modular synths :P 

Great work on this, seriously love the UI and this is really fueling my JUCE learning process.. Thank you so much for making such an awesome opensource JUCE synth!

**Comment by mtytel** [comment]
Yeah I've already got a fix for this but it's not released yet.
Thanks for the report and the kind words!
