### ISSUE TITLE
How to tell Helm to only respond to a single MIDI note?

### ISSUE THREAD

**Issue by brylie** [mtytel/helm#202]
I am using three instances of Helm as voices in a drum kit in Ardour. E.g. I have a kick, snare, and hi-hat. I have set all of the Helm instances to receive messages from a single MIDI sequencer track, so I can sequence them all on the same piano roll. However, all of the Helm synths are responding to all MIDI notes. How can I tell an instance of Helm to respond only to a specific MIDI note?

**Comment by baderbuddy** [comment]
There might be a midi plugin in Ardour that can filter down to particular notes for you, or I know in Reaper you can set the channel of individual notes and then only send one channel to a given track, that should accomplish what you want. I think this is more of an Ardour question than a Helm question though.

**Comment by mtytel** [comment]
Yeah I would leave this up to a utility or DAW feature.
