### ISSUE TITLE
Helm sampler?

### ISSUE THREAD

**Issue by naught101** [mtytel/helm#204]
I've been looking around for a decent sampler plugin along the lines of simpler in ableton, and it struck me that helm with the oscillators replaced with an audio player would make a pretty great sampler that would be really, really useful for re-sampling, and wavetable synthesis..

Basically the audio player would need:

- start, end, and loop points
    - loop fade/mix length, [maybe start and end fade-ins to prevent clicks? or loop-point zero-crossing snapping?]
    - looping mode (loop, one-shot, ping-pong), reverse
- key/pitch, fine-tune, [and maybe keytracking width?]
- volume

It already has an ADSR, filter, portamento, unison, basic effects, and all the modulation you'd ever want.

If allowed 2+ audio files, you could do morphing wavetable synthesis, too, I guess. That might be nice for a later version

I'm considering having a play around making a plugin like this later in the year, and basing it on Helm seems like a pretty good option at the moment. If this sounds like something that would be useful *within* Helm, I could do it as a pull request. If not, I'd appreciate any advice/insight/warnings you might have for doing it as a separate project.

**Comment by mtytel** [comment]
Yeah I'm not going to add larger features like that to Helm. Probably will have a sampler in my next synth but probably won't have loop points or anything. we'll see though.
