### ISSUE TITLE
Feature Request: MPE Implementation

### ISSUE THREAD

**Issue by Ekolide** [mtytel/helm#205]
The MPE spec was adopted by the MIDI foundation a while back and it would be cool to see it implemented in Helm.

https://www.midi.org/articles/midi-polyphonic-expression-mpe

**Comment by wolftune** [comment]
I support this, but it's a duplicate of one I already opened https://github.com/mtytel/helm/issues/158 so this should be closed.

**Comment by mtytel** [comment]
I have a seaboard block coming in the mail so maybe soon :P
