### ISSUE TITLE
Formant strength, shift, and spread.

### ISSUE THREAD

**Issue by naught101** [mtytel/helm#206]
The formant filter is cool, but it's not all that useful, because it's set to a standard set of formants, which means that it doesn't do much of most of the interesting harmonics are in a lower or higher range than specified by those formants.

It would be awesome to have a few extra parameters:

- Strength: basically a multiplier on the gains of all filter peaks.
- Spread: a multiplier that spreads the individual peaks out from the middle of their range (the average frequency of all the peaks)
- Shift: a bias that shifts all of the peaks together up or down the the frequency spectrum.

When I've made a custom formant filter in Bitwig using modulated EQ, I've found that the last parameter especially has a really awesome effect - it basically means that you can get a really low voice-lice sound, without cutting all the bass out as the current filter does.

The "strength" parameter could also help with https://github.com/mtytel/helm/issues/159

**Comment by mtytel** [comment]
I'm not implementing any big changes into Helm anymore outside of bug fixes.
All major improvements like this are going into a new synth coming next year. Keep an eye out!

**Comment by naught101** [comment]
OK, fair enough. Does that mean that you wouldn't accept a pull request for something like this? I guess I can always just implement this in my own fork, if that's the case.
