### ISSUE TITLE
GUI Display Issues

### ISSUE THREAD

**Issue by ghost** [mtytel/helm#207]
![image](https://user-images.githubusercontent.com/14898345/44639614-81017880-a982-11e8-8370-2ec0d756c5fd.png)

Opening Helm as a standalone application has no problems, however when using it as a VST, it does not display properly. 

Win10, FL Studio 20. 

I don't know where to start, I tried repairing it using the installer and it didn't work. I have had this problem from the get go, so it is not a temporary thing. I'd be happy to provide any other information needed to solve this. Thanks, -Zach

**Comment by mtytel** [comment]
This is actually already fixed but I haven't released a new version yet.
The bug has to do with OS scaling in FL Studio. If you set Windows OS scaling to 100% in Settings -> Display, log out, then log back in it'll work.

Or just wait for the next release and it'll work as well.

**Comment by ghost** [comment]
Awesome, thanks for the cool plugin.

**Comment by Snazzie** [comment]
Hi i have the same issue, im using a 1440p monitor at 125% scailing.

I dont want to reduce to 100% as then everything is too small. please fix this scailing bug properly :/

**Comment by CRTX** [comment]
Hi, I have this same issue in Bitwig currently. It is completely broken in Bitwig 4.3 when you try to resize the VST window.

It works in Linux as reported by another Bitwig user in discord (using native Bitwig binaries) but for me, it does not work under Windows 11.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1076285/179532567-3fee37cf-290c-4058-ac05-ab9a35fc6cbf.png">

**Comment by Snazzie** [comment]
Not a solution to your problem but if you didnt know already, helm hasnt been in development for ages as they released [Vital](https://vital.audio) which is also free but way better.

**Comment by CRTX** [comment]
@Snazzie The same thing happens in Vital lol. But it's ok, turning off "Interface scaling" in Bitwig plugin options fixed the issue.
