### ISSUE TITLE
Arpeggiator doesn't scale with sample rate in Ardour5

### ISSUE THREAD

**Issue by aeonik** [mtytel/helm#209]
Hello,
The arpeggiator does not scale properly with different sample rates. The faster the sample rate, the faster Arp notes play.

This can be replicated on my system by:
1. Creating two test projects in Ardour5
1a. Project 1 sample rate is set to 44.1 KHz
1.b Project 2 sample rate is set to 48 KHz
2. Create the same MIDI track with 4 whole notes. 
3. I configure Helm Arp to 1/4 quarter note frequency. 
4a. Project 1 plays an expected 4 notes.
4b. Project 2 plays 5 notes, off time.

This bug scales with sample rate: the faster the sample rate, the more erroneous notes play. This affects both my Arch and Ubuntu systems. Helm v 0.9.0, Ardour v 5.12.0

Regards,
Aeonik

**Comment by gonX** [comment]
Might be the same as #182?

`community/helm 0.9.0-7` on Arch has that issue, but git does not.

**Comment by aeonik** [comment]
Sebastian,
It looks like the same issue. Great find!

I can build the Git version on my Arch system tonight to confirm this
hypothesis.

**Comment by mtytel** [comment]
Yeah I haven't released a new build in a while..
I've been busy working on Helm's successor!

**Comment by Bleuzen** [comment]
@mtytel Will you keep Helm maintained?

**Comment by aeonik** [comment]
Matt,
Thanks for sharing the news! I can't wait to see what you have in store.
Let us know when it becomes available.

-Aeonik

**Comment by unfa** [comment]
I think I just hit this bug. I'm always running at 48 kHz - and Arpeggiator is too fast for my session's tempo, even though it correctly got 140 BPM.

**Comment by rburgosnavas** [comment]
Just noticed this error too. The arp is slightly faster than the track's tempo on Renoise (Linux)

**Comment by jpriebe** [comment]
I saw the problem on Ableton Live / Windows 10.  Using a sample rate of 44100, the arpeggiator was synced with tempo.  When I changed it to 48000, the arp was out of sync.  Helm's LFOs, stutter, and sequencer were fine, however.

**Comment by xard-dev** [comment]
As I experimented with updating JUCE to 5.4.7 I noticed that this bug seems to be gone from the build using the newer JUCE when tested on 48 kHz project in Ardour. Now the arpeggio is in sync as expected.

**Comment by xard-dev** [comment]
The patch is in form of pull request now.
