### ISSUE TITLE
Change "Linux" to "Debian/Ubuntu" on website

### ISSUE THREAD

**Issue by metal3d** [mtytel/helm#212]
Hi,
Please don't read my issue as aggressive, but I was disappointed to get a .deb file when I started to download the "Linux" version. You should change the label to specify that is only for Debian and derived.

Consider that some users can pay before to get the release and to be unable to install it after downloading the package.

I will compile Helm myself while I'm on Fedora, if you want me to create a RPM, I can do it (I guess).

Thanks !

**Comment by metal3d** [comment]
I did 2 RPM here for Fedora 28:
- helm-standalone
- helm-lv2

Both are working on my own computer. That was not so easy to find dependencies but it's now ok. I can prepare a "copr" repository if you're interessed.

While I understand you want to have donation to provide packages, is it a problem if I propose my package on Fedora Copr ? https://copr.fedorainfracloud.org/

**Comment by mtytel** [comment]
Yeah I should put (.deb) next to it or something, thanks.

Please go ahead and put in on that Fedora website.

**Comment by metal3d** [comment]
Hi, ok I'm creating the repository on Copr.

Anyway, to discuss about the "Linux" term vs. Debian/Ubuntu, it's a real problem that I see on several projects. My message was mainly written to prevent that kind of amalgam. 

If you need the RPM to have donation from your website, I can give you src.rpm and explain how to build it, and how to serve it. So you will be able to provide them with .deb packages.

**Comment by metal3d** [comment]
Note: I'm fixing some details to have screenshots in the RPM GUIs and I will send the RPM on Copr, then I will be able to give you .spec or .src.rpm files

**Comment by trebmuh** [comment]
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/

**Comment by metal3d** [comment]
@trebmuh yes, seen... Mine is sperated on 2 packages (lv2 and standalone) respecting name convention... So if someone is interessed:
https://copr.fedorainfracloud.org/coprs/metal3d/helm/

**Comment by BrunoVernay** [comment]
I just build Helm (and ZynFusion) before reading this ...
It would be nice to have a wiki page or a chapter in the readme about the dependencies ( libcurl-devel libXinerama-devel libXcursor-devel ... ) for example :-) and the link to the COPR.
Also it crashes on Wayland? I had to use Xorg ...

**Comment by metal3d** [comment]
Seems to be dead...
