### ISSUE TITLE
Want to programmatically record audio from synth 

### ISSUE THREAD

**Issue by vaidarnav** [mtytel/helm#222]
Specifically I want to load a custom preset file, then record the audio output from the synth given a midi file I provide as input. I want to do this for a bunch of different presets and midi files. What methods/APIs should I look at in order to do this efficiently?

**Comment by baderbuddy** [comment]
This might be a task that's better suited for a DAW, there are several out there that have free trials or versions available and most DAW will allow you to add a VST instrument, supply it with some MIDI, save some preset settings for it and then record the output audio.

**Comment by vaidarnav** [comment]
Is there really no way to do this without a DAW? I'd be really interested in how realtime audio synthesis from midi is realized.

Are there any free (and simple) daws that allow programatic recording that I could use as an alternative? I've been looking into Reaper with its ReaScript and while I can do preset loading its not clear to me that it supports midi to audio synthesis.

**Comment by mtytel** [comment]
I mean most DAWs are pretty much designed to do this. Though doing it programmatically is a little harder to find.

If you want to go the programming route I'd probably look at Pure Data / Max MSP.
I know you can load vsts in them and should be able to do audio out to a file but I don't know how well they handle MIDI files.

Going to close this because it's outside the scope for Helm.

**Comment by txntxn** [comment]
We also would like this feature.

One of the beautiful core tenets of Helm is that it is open-source and designed to run on a variety of platforms, including in standalone mode. We have been searching high and low for a high-quality synth that we can control programmatically, and sadly they do not exist.

We would love it if Helm were to acknowledge that it should be available to everyone to use, including other computer programs.
