### ISSUE TITLE
Will this be seeing any new commits and releases?

### ISSUE THREAD

**Issue by Jacalz** [mtytel/helm#228]
Right now it seems like not a lot is happening, is there anything new on that front?
I think this project has a lot of potential and I don't want to see it die...

@mtytel

**Comment by Jacalz** [comment]
It would be wonderful if we could get a 1.0 release so this can be marked as stable :+1:
This would make it possible for inclusion in to Solus and well it isn't much work :slightly_smiling_face:

**Comment by mtytel** [comment]
Yeah sorry. I've been working on a new synth and it's taking a lot of my time! https://twitter.com/matttytel/status/1142221431364702208
I'll set aside some time to make the builds for 1.0 soon.

**Comment by Jacalz** [comment]
Wonderful seeing that this isn't dead and thanks for the fast response :+1: Will follow along with the development and it will be interesting to see the new synth when it gets released :slightly_smiling_face:

**Comment by Jacalz** [comment]
Will the new synth be open sourced on GitHub soon?
If so, I have both that and this 1.0 release to look forward to :)

**Comment by Jacalz** [comment]
Any news on the state of the 1.0 release? I am looking forward to getting this released in the Solus repository :slightly_smiling_face:
