### ISSUE TITLE
Compilation problem on current master

### ISSUE THREAD

**Issue by ycollet** [mtytel/helm#23]
Hello,

I use fedora 21 64 bits.
I meet a compilation error with the current master:

Compiling juce_video.cpp
make[2]: *** No rule to make target '../../../JUCE/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp', needed by 'build/intermediate/Release/juce_LV2_Wrapper_fb90cd9c.o'. Arrêt.
make[2]: Leaving directory '/home/collette/repositories/helm/builds/linux/LV2'
Makefile:8: recipe for target 'binary' failed
make[1]: *** [binary] Error 2

Best regards,

YC

**Comment by mtytel** [comment]
Ah thanks for catching another one! Accidentally pulled from the wrong JUCE repository from Mac.
I should get a better build system going. Manually building and testing on each OS is getting tedious and I'm making mistakes..

**Comment by mtytel** [comment]
Fixed!
