### ISSUE TITLE
GUI is corrupt when using inside Renoise 3.2

### ISSUE THREAD

**Issue by spectromas** [mtytel/helm#234]
Just updated to Renoise 3.2, which has HiDPI/scaling options, but Helm's GUI window just shows scrambled squares. I reported it [here](https://forum.renoise.com/t/windows-helm-gui-shows-as-corrupt-in-3-2) but the Renoise dev mentions that it can only be fixed by the plugin author. 

No other plugin I've tried has this issue.

**Comment by mtytel** [comment]
it's an opengl and Windows OS scaling thing. It's possible for them to fix it because other hosts are fine.
Anyway I found a workaround that's already in the code base. Just need to make a new release.

**Comment by cyanit** [comment]
Hi,
unfortunally this issue is still present for me. Have you updated the binaries already?
Have a nice day!

-----
![image](https://user-images.githubusercontent.com/26248671/69574364-3a0c9380-0fc8-11ea-84d6-ea622495857c.png)
(4k, Windows 10, Bitwig Studio)
