### ISSUE TITLE
GUI error on Waveform 11

### ISSUE THREAD

**Issue by ghost** [mtytel/helm#246]
Hello,
It seems that Helm has some issues while opening inside Waveform DAW.
Here is a sample-
without DPI awareness:
![ABC1](https://user-images.githubusercontent.com/9512421/77823442-42650e80-7121-11ea-8da8-3e97b6fc0faa.jpg)
with dpi awareness
![ABC2](https://user-images.githubusercontent.com/9512421/77823448-4a24b300-7121-11ea-9675-6ab7078c6864.jpg)
Any diy fix?
I could do some basic fixes tho...
Thanks

Edit: Works without any problem in LMMS , only problem is the inbuilt marco and drop-down , I guess it has to do with the damn DAW itself.

**Comment by DavidsonAudioMulti** [comment]
Here is a work around for window right click on your host properties DPI settings and switch to high dpi scaling override set system advanced for your host DAW. Here is a Guide https://reaperblog.net/2019/12/workaround-tiny-vsti-r6/
