### ISSUE TITLE
Maintainer needed?

### ISSUE THREAD

**Issue by StarWitch** [mtytel/helm#258]
I'm noticing that there have been no new commits in 2 years, open issues haven't been responded to or triaged, and PRs for compile-time errors such as #233 are going without any response despite multiple requests and +1s. 

@mtytel Is there a need for an additional maintainer, to help things along?

**Comment by mtytel** [comment]
I've been busy working on a new project, will update Helm when I have time.

**Comment by dvzrv** [comment]
@mtytel AFAICS the question was more aimed at providing help to you and this project, so that the responsiveness of it can be increased.

This situation is not optimal for users and packagers alike.
