### ISSUE TITLE
Packaging for openSUSE/Leap 15.2

### ISSUE THREAD

**Issue by josegomezr** [mtytel/helm#263]
Hi There!

I'm packaging helm for openSUSE Leap (for now since Tumbleweed fails to compile due to GCC >9 incompatibilities).

You can [check it out here](https://build.opensuse.org/package/show/home:josegomezr/helm-synth)

https://build.opensuse.org/package/show/home:josegomezr/helm-synth

It's a bit of a work in progress, but you should be able to download a functional RPM by now.

**Comment by idoleat** [comment]
Thanks for your work!
