### ISSUE TITLE
I tried to build helm for armv7hl and it didn't like it.

### ISSUE THREAD

**Issue by Baggypants** [mtytel/helm#27]
Well, I tried to build Helm on Fedoras koji buildsystem and it didn't like it.

output from the build is here
https://kojipkgs.fedoraproject.org//work/tasks/4269/10784269/build.log
 Things it doesn't seem to like are
g++: error: unrecognized argument in option '-mtune=generic'
g++: error: unrecognized command line option '-msse'
g++: error: unrecognized command line option '-msse2'
g++: error: unrecognized command line option '-mfpmath=sse'

For now I  may try to exclude armv7hl in the builds.

**Comment by mtytel** [comment]
Hmm.. I put those flags in to speed up the build, but they really didn't have any effect I could see.
Removed them, let me know if you run into any more issues!
