### ISSUE TITLE
JUCE might not like armv7hl

### ISSUE THREAD

**Issue by Baggypants** [mtytel/helm#28]
The armv7hl build still failes but it's not got any nice obvious easy-to-read errors

https://kojipkgs.fedoraproject.org//work/tasks/2387/10822387/build.log

**Comment by mtytel** [comment]
Hmmmmm. Might be my configure script. It's just a place holder right now, but should modify the Makefile. Maybe I'll bite the bullet and move this project over to autotools..

**Comment by danboid** [comment]
I'm pretty sure this can be closed now, right Matt? A number of people have successfully got JUCE and Helm building on ARM.

**Comment by mtytel** [comment]
Yup. Thanks
