### ISSUE TITLE
LV2: BPM locked to 120 when used in DAW

### ISSUE THREAD

**Issue by tcrass** [mtytel/helm#283]
Hi there,

whenever I use Helm (0.9, either from Matt's download page or from the KXStudio repo) as LV2 plugin in Qtractor (0.9.19) or Ardour (6.5), Helm's bpm setting seems to be locked to 120. Mind, I'm not talking about the setting being synchronized to the corresponding DAW setting -- it's literally locked to 120 bmp, whatever tempo the DAW has been set to! When moving the Helm plugin's bpm slider, it immediately jumps back to 120.

Stand-alone Helm doesn't exhibit this behavior.

Anyone else experiencing this issue?

Cheers --

Torsten

P.S. I'm on an up-to-date Debian Buster system.

**Comment by mfs12** [comment]
The bpm is set by the DAW. At least in Ardour it works like this. Try changing DAW's bpm and helm should adopt the value.

**Comment by tcrass** [comment]
As opposed to my initial impression, it does indeed work in Ardour. I double-checked with Qtractor, but here the described problem remains. I guess I'll have to bug Qtractor's developer about this again...
