### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by reaswi** [mtytel/helm#298]
The installer installe mostly versions that I don't want on my computer.  If possible please use an installer that lets me pick what I want to install.
I will use this and pay for it after that.  Until then...  It looks and sound great.  It's just to much garbage for me to want to deal with all the extra crap.
If I could find where it installed on my computer that would help too but all I found was as .exe file in program file/ helm.
nothing in common files or where it said it would install the vst2 version(that I don't want)

**Comment by mtytel** [comment]
Closing because this has nothing to do with the code.
