### ISSUE TITLE
Can't save patches

### ISSUE THREAD

**Issue by ssj71** [mtytel/helm#3]
The default save location is /usr/local/share (or /usr/share depending on how its packaged/installed) and ubuntu doesn't give write permissions to that directory. So if you try to save in the default, nothing is there, if you try to save somewhere else you can't find the patch again.

**Comment by mtytel** [comment]
Thanks for finding a real embarrassing bug. I'll have this cleaned up asap.

**Comment by mtytel** [comment]
This was unique to GNU/Linux. Should work in the next release 0.3.5.

**Comment by mtytel** [comment]
Patches are now saved to "~/.helm/User Patches"

**Comment by ssj71** [comment]
perfect. thanks for the speedy response!
