### ISSUE TITLE
Build output is non verbose

### ISSUE THREAD

**Issue by Baggypants** [mtytel/helm#30]
Apparently this matters if you're trying to get it put in as an official package in Fedora. I tried to learn make to write a patch and save you some work but apparently I suck at learning make.

Packaging comments here.
https://bugzilla.redhat.com/show_bug.cgi?id=1250833#c6

**Comment by mtytel** [comment]
Aw maaaaan. I really like non-verbose make. Looking into this but it's an auto generated Makefile so I don't know how easy it is to change.

In case you're curious:
It's the '@' character in front of each command in the Makefile that silents the reprinting of the command to the terminal. The echo command actually prints to the terminal but if the '@' character wasn't there the entire command 'echo "Compiling juce_opengl.cpp"' would be print to the screen

    $(OBJDIR)/juce_opengl_a5fa29cd.o: ../../../JUCE/modules/juce_opengl/juce_opengl.cpp
      -@mkdir -p $(OBJDIR)
      @echo "Compiling juce_opengl.cpp"
      @$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

**Comment by Baggypants** [comment]
You could keep the non-verbose mode, patches can be applied at packaging time to satisfy the the Fedora elite :D thanks for the tip, I'll look into it.

**Comment by mtytel** [comment]
Alright I got an easy solution for this now. Committed to the development branch.
All you need to do when you invoke make is define the variable VERBOSE.

e.g.
    $ make VERBOSE=1
