### ISSUE TITLE
GUI size problem on 1920x1080 monitor

### ISSUE THREAD

**Issue by asbaklm** [mtytel/helm#32]
On 1920x1080 displays using Linux, the helm gui appears to be very oversized (as if it were zoomed in) with the result that most of the parameters cannot be accessed.

It displays fine on another laptop with a different (lower) screen resolution which makes me wonder whether this is something to do with this specific resolution setting.

**Comment by mtytel** [comment]
Strange, I can't reproduce this.
A couple questions so I can try to narrow it down.

Is the pixel density on the 1920x1080 display 72dpi?
Are you using any non-standard window managers?
Also, could you post a screenshot?

**Comment by asbaklm** [comment]
I'm not sure how to obtain the pixel density, one affected monitor is a Samsung Syncmaster P2450. Here's the screenshot, thanks for looking into this!  

It was loaded with jalv.gtk on a 64bit Linux Mint installation. Other lv2 instruments display OK.

![helm](https://cloud.githubusercontent.com/assets/8843057/10586340/93156146-7693-11e5-8b90-7d50e15c24f3.png)

**Comment by osune** [comment]
Can confirm. 
Display: Samsung Syncmaster
DPI: 92x91
WindowManager: Awesome Wm
Running Arch Linux and helm-git 0.5.0.r1105.ad798d4-1

**Comment by asbaklm** [comment]
I tried changing resolution but the problem persists. 

This happens on a Debian Jessie 64bit system + Cinnamon + Samsung monitor and a Mint 17.2 64bit + Cinnamon + Samsung monitor. 

On an older Mint 17 32bit Lenovo laptop the GUI displays normal.

**Comment by mtytel** [comment]
Hmm, this might be a multiple monitor issue because I'm doing some GUI sizing based off the "main" display.. Do both of you have two or more active monitors when using Helm?

**Comment by asbaklm** [comment]
On one system I have multiple monitors, on the second affected system there's only a single display. 

System 1 = LM17.2 64bit, Samsung + Viewsonic monitors, KXStudio
System 2 = Debian Jessie 64bit, Samsung display, KXStudio

Both use Samsungs as main displays. I haven't come across this issue with other plugins, it seems to be unique to Helm.

As a temporary workaround I've loaded the windows version of helm via wine/dssi-vst and that displays normally.

**Comment by osune** [comment]
Sorry for the late reply.

No second monitor in use here.

As for another note if it helps, I'm using the proprietary Nvidia driver.

**Comment by asbaklm** [comment]
For what it's worth, I'm using oibaf AMD drivers

**Comment by mtytel** [comment]
Alright, still not sure what the problem is, but next build I'm making the GUI resizable which should be an ok temporary fix. It's going look a little fuzzy this time around though.

**Comment by asbaklm** [comment]
I built VST and LV2 versions today of Helm from the current version in git on LM 17.3 64Bit w. Cinnamon desktop . Here's what's currently happening.

- When loading Helm VST or LV2 in Carla (built from recent git) on the primary or secondary displays, GUI's are still oversized and there doesn't appear to be a way to work around this. Also, Helm + Carla appear to be crashing & throwing jack exceptions when hosted in Carla (jack2, built from git). I don't see this happening with other softsynths in Carla. I'll create a separate ticket for that.

- When alternately opening and closing the Helm LV2 GUI in Carla on the secondary display at 1280x1960, the Helm GUI cycles in an inconsistent way between the correct size and different variations of unusable oversized screens. So by keeping on opening and closing the GUI it may eventually chance on the correct size. (If it doesn't crash first with Carla).

- When loading Helm LV2 in Carla on the secondary display, dragging it over to the primary display and closing and opening the Helm GUI multiple times, Helm sometimes ends up being the correct size by chance, or it settles on an unusable size and doesn't change on further opening and closing attempts.

- When loading Helm LV2 with jalv.gtk in the secondary display set at 1280x960, the Helm GUI is intermittently at the correct size and oversized, and I don't know of a way to reproduce results consistently.

- When loading Helm LV2 with jalv.gtk in the primary display at 1920x1080, the GUI is oversized.

- When loading Helm LV2 in Muse 3 compiled form latest git, the Helm GUI takes up the entire screen although it becomes almost usable because only the right and bottom border areas are extending off screen.

- The behaviour of the Helm GUI size is inconsistent and can be affected by opening and closing the GUI from inside a host application such as Muse3 or Carla.

- There appears to be stability issues with Helm + Carla.

**Comment by osune** [comment]
Hoi,

latest Tests show following behavior:

* Helm Standalone works fine ( your temporary fix works so far? )

* Helm loaded in Carla (LV2 and VST) still shows only a zoomed in part of the UI

* Helm loaded in Renoise3 still shows only a zoomed in part of the UI

* Helm loaded in Renoise3 via CarlaRack plugin still shows only a zoomed in part of the UI

To cut a long story short:
When hosted Helm still has size issues.

Tested with Helm 0.6.1.r6942.8773808-1

PS: thanks to working standalone version i was able to use the synth for the first time and i love it =)

**Comment by mtytel** [comment]
I've redone GUI resizing. Should be waaaay better now.

**Comment by mtytel** [comment]
Will come out in next version (0.9)
