### ISSUE TITLE
My compliments!    :)

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#35]
I have a coupe of actual issues (which I'll file after this), but first I wanted to say:

WOW!!!  Great work!!!

In particular I love:
- great sound
- some novel algorithms (afaik): <3 the filter feedback tuning and osc cross modulation
- not dumbing it down too much (plenty of knobs and options)
- no useless frills on screen, everything there has a function
- almost anything to anything modulation.  It's great fun having dry/wet of an FX modulated by an LFO.
- great visual feedback on the modulation

Thank you!!!!   :)

**Comment by mtytel** [comment]
Whew! Thanks for the kind words and all the feedback!
I'm going to have my hands full for a while :D
