### ISSUE TITLE
feature request: different scaling of some parameters.

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#38]
In particular:

-step sequencer to LFO tempo modulation is to sensitive: a small modulation leads to a too big change in tempo, making it hard to controll
-Step smoothing has a too wide range, making it hard to use as well.

**Comment by mtytel** [comment]
Yea, modulating frequency is whack right now. I'll change that.

I'll see what I can do about step smoothing too.

**Comment by magnetophon** [comment]
Thanks.

**Comment by mtytel** [comment]
Well this was a while ago but I fixed modulating the frequency of things. Now it modulates before the exponential scaling of the setting. It's still a little sensitive so I might change this more in the future.
Step smoothing should be better too.

**Comment by mtytel** [comment]
Will come out in the next version.
