### ISSUE TITLE
formant filter increases volume

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#39]
when you enable the formant filter, the synth gets a bit louder.
I understand this probably depends on the signal going into it, but I'd say it's better to err on the side of too soft; after all, it's a filter, taking away part of the sound.

**Comment by mtytel** [comment]
Yes, I really don't like the formant filter right now. I've been meaning to fix and just rework the sound overall.

**Comment by mtytel** [comment]
The formant filter sounds waaaaaay better now.
