### ISSUE TITLE
feature request: more stereo options.

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#40]
A synth typically sounds much bigger when it's not just the effects that make it stereo.

On the top of my list are:
-stereo spread for unison, like ZynAddSubFX.
-phase offset for LFOs: in many chorus plugins, you can set the phase offset between the LFO modulating the left signal, and the one modulating right. Combined with Helms flexible modulation options, this would lead to some awesome sound-design possibilities.

I realize this would probably double the dsp load, but IMHO that's worth it.

**Comment by mtytel** [comment]
Hmmm. I'll need to think about this since it'll require a little restructuring.

**Comment by magnetophon** [comment]
Thanks for considering.
Off all my feature request, this one excites me most.

**Comment by magnetophon** [comment]
A modulateable panner would be the icing on the cake.
It's nice to pan a sound with notes or with an lfo...  :)

**Comment by rghvdberg** [comment]
+1 :+1:

**Comment by spectromas** [comment]
I just wanted to add +1 to this too, some kind of a stereo expander (like Massive's) would be nice, as well some stereo options for the delay (ping pong etc).

**Comment by mtytel** [comment]
From @unfa

> Ideas for improvement:
> 
>     Pan/width controls for sources in the Mixer (Ardour Style?)
>     Or Width controls for Unison in oscillators 1 & 2 and Pan controls in the mixer.
>     Noise generator stereo width control.
>     L/R time difference for delay effect.
>     L/R pitch difference fro Feedback.

**Comment by unfa** [comment]
I've found a way to workaround the limitations in Ardour, by using 2 instances of helm, but it doesn't always sync the changes in the patch between both instances right:

https://www.youtube.com/watch?v=lNQH2p0KnCY

**Comment by magnetophon** [comment]
@unfa thanks. I was sometimes doing this manually with midi busses.  Your solution is much more user friendly.
@mtytel The video gives a nice audio demo (at [this time](https://youtu.be/lNQH2p0KnCY?t=302)) of the kinds of sounds I was hoping to get.

**Comment by mtytel** [comment]
Trimming features that won't ever go into Helm.

I've got some crazy stereo options in my next synth though. Fully stereo chain and lots of new stereo modulation options.

**Comment by magnetophon** [comment]
You sure did come trough on that one, Vial has all the stereo options I was dreaming of, and more!
Thank you!!!!
