### ISSUE TITLE
feature request: on/off buttons for sources.

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#41]
While designing a patch, it is often useful to be able to switch off individual sources:
-osc 1 and 2 individually  (but keeping the cross-modulation)
-sub
-noise

**Comment by mtytel** [comment]
You're on the development branch build right? The mixer doesn't fulfill this need?

**Comment by magnetophon** [comment]
I'm on the master branch, rev ad798d4a0a2e7db52e1a7451176ff198a393cdb4
I'll check out the development branch.
The mixer will probably fill this need, I'll re-open the issue if it doesn't.
Thanks!
