### ISSUE TITLE
mod envelope is mostly invisible

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#43]
I played with Helm all night, never once seeing the mod envelope.
While filling out these bug reports, it all of a sudden popped up.

It seems like it's not supposed to show up, since it's on it's own in the bottom of the window, with empty space left and right of it.
I <3 it anyway!  :)

**Comment by mtytel** [comment]
Ah yea. You're building off of the development branch right?
I'm working on moving some things around right now so it'll fit in better.
Should be done soon.

**Comment by magnetophon** [comment]
I'm on master rev ad798d4a0a2e7db52e1a7451176ff198a393cdb4
I guess that explains why I mostly didn't see it, but begs the question why I did see it.
Anyway, the fact that is WIP is enough info to close this issue, I think.
