### ISSUE TITLE
The i3 window manager cannot drag the Helm window.

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#44]
In i3, windows can be floating, and when they are, you can drag them around by pressing a modifier key.
Helm simply ignores this.  I've never seen another window do this in i3.

**Comment by mtytel** [comment]
Hmm. I can drag it around in the awesome window manager fine.
I'll have to download i3 and try it out. It could be a bug in the framework I'm using (JUCE)

**Comment by mtytel** [comment]
Hmmm. I can drag it from the bar at the top but it doesn't like dragging on top of the UI. Not really sure why that is..

**Comment by suhr** [comment]
Hm, I use i3wm too but can't reproduce this.

**Comment by magnetophon** [comment]
@suhr I also use win, so that's not it.

Maybe it;s version related?
I'm on i3 version 4.10.3

**Comment by suhr** [comment]
I'm on i3 v4.11.

**Comment by badosu** [comment]
I can reproduce this error on i3 v4.13

**Comment by mtytel** [comment]
This works now on the development branch.
Will be out in the next version.

**Comment by magnetophon** [comment]
@mtestytel thanks!
I'll test soon!
