### ISSUE TITLE
feature request: external audio input

### ISSUE THREAD

**Issue by magnetophon** [mtytel/helm#45]
It would be nice if the filter and FX could be used on external sources.
Even nicer if the external sounds could cross-modulate the oscs.

**Comment by mtytel** [comment]
Hmm. Yea this would be nice, but I don't think I'm going to get around to it before the 1.0 release. I'll mark it as a v2.0 feature.

**Comment by mtytel** [comment]
Trimming features that won't ever go into Helm.
Putting this on the list for a new synth in the works.
