### ISSUE TITLE
Pitchwheel doesn't work

### ISSUE THREAD

**Issue by ssj71** [mtytel/helm#5]
Pitchwheel has no default effect. I actually like the prospect of being able to map it to anything, but I'd like the default do the usual thing. I had to map it to the tune parameter of each osc and that works exactly as expected. 

Also the pitch bend parameter in articulation has no effect.

**Comment by mtytel** [comment]
Looks like the pitch wheel signal got lost somewhere. I'll go find it.

**Comment by ssj71** [comment]
I could hang up flyers on the street corners for ya :)

**Comment by mtytel** [comment]
Fixed and pushed! Next release will have it.

**Comment by ssj71** [comment]
awesome! Thanks!
