### ISSUE TITLE
Optimize oscillators

### ISSUE THREAD

**Issue by mtytel** [mtytel/helm#56]
They're currently the largest CPU hogs in the synth.

**Comment by avish** [comment]
It seems to me like some non-trivial amount of CPU could be saved by bypassing unused components like oscillators with a mix level of 0, LFOs/envelopes with no modulation targets (and env depth == 0), etc. 

Also, for true bypass-enabled modules (delay, arp etc.), the bypass causes the input buffer to be copied to the output buffer, but maybe this could be saved by simply using the input buffer AS the output buffer? Not sure how feasible that is in mopo's architecture.

**Comment by mtytel** [comment]
I've gone through and turned a lot of things off when Helm isn't using them. This helped, but the oscillators still used up a lot of CPU.

I've tried SIMDing the oscillators but the cross mod prevents that from happening. I'm going to mark this as done but in version 2 of Helm I'll probably come back and redesign the oscillators since I don't even like the cross mod that much anyway.
