### ISSUE TITLE
State is not saved in Ardour session

### ISSUE THREAD

**Issue by Fak3** [mtytel/helm#57]
Steps to reproduce:
* Start Ardour with new session
* Add MIDI Track with Helm as instrument
* Choose any profile from bank
* Restart Ardour, saving session
* Open saved session

Result: Helm state is reset to default.
Expected Result: Helm should restore its state, corresponding to prevoiusly opened profile, saved with session.

**Comment by Fak3** [comment]
Oh, I am using Ardour 4.4 on Linux with Helm 0.5.0

**Comment by mtytel** [comment]
Hmm I tried your steps to reproduce but it's mostly working for me. I do see some modulation connections not loading (see https://github.com/mtytel/helm/issues/36), but the waveforms load back the same, and all the knobs are set to the last positions.

Is there any more information you could give me about your setup or what you're doing? Does saving with other plugins work fine for you?

**Comment by mtytel** [comment]
One other question, are you using the VST or LV2 version?

**Comment by Fak3** [comment]
Oh. Yes, i was wrong. Only the modulation connections are lost.
Closing this as issue #36 already reported.
