### ISSUE TITLE
distorted sound when playing 3 and more keys at once

### ISSUE THREAD

**Issue by suedwestlicht** [mtytel/helm#6]
It's audible even with the init patch. Just increase the number of voices and play a chord. Lowering volume doesn't help but lowering sustain level in AMPLITUDE ENVELOPE helps, at least in the sustain stage.

**Comment by suedwestlicht** [comment]
I forgot: I fetched Helm from github and compiled it on Xubuntu 12.04 64 Bit

**Comment by mtytel** [comment]
Yea, that's the soft clipping coming in to prevent a hard clipped signal. I see how it's a problem. I need either to have a global "Gain" control or something that scales the signal before distorting. Volume scales after distorting. Thanks!

**Comment by mtytel** [comment]
Whoooo, this took a long time to do.

I added a mixer into the oscillator/sub/noise section. Also changed the distortion a bit.
It'll still distort if you hit enough notes, but you can just drop the mixer values to compensate.
Going to add a volume meter as well for some visual feedback.

These changes are currently in the development branch.
