### ISSUE TITLE
compilation of standalone Lv2 fails because xrandr.h is missing.

### ISSUE THREAD

**Issue by taffy-nay** [mtytel/helm#61]
```bash
Compiling juce_gui_basics.cpp
../../../JUCE/modules/juce_gui_basics/juce_gui_basics.cpp:110:37: fatal error: X11/extensions/Xrandr.h: No such file or directory
   #include <X11/extensions/Xrandr.h>
                                     ^
compilation terminated.
Makefile.binary:755: recipe for target 'build/intermediate/Release/juce_gui_basics_3e4cc581.o' failed
make[1]: *** [build/intermediate/Release/juce_gui_basics_3e4cc581.o] Error 1
make[1]: Leaving directory '/home/user/Projects/helm/builds/linux/LV2'
Makefile:8: recipe for target 'binary' failed
make: *** [binary] Error 2
```

**Comment by mtytel** [comment]
Hmmm. Apparently Xrandr.h is needed for some multimonitor linux support.
If you need to build without Xrandr.h you can pass this command line flag into the build `-D JUCE_USE_XRANDR=0` and it should build without it.

**Comment by falkTX** [comment]
I think you should disable that actually.
Is there any reason for requiring that for a plugin?

**Comment by mtytel** [comment]
I can disable it. But it sounded like it would break multi monitor support.
I had thought that meant it wouldn't work with multiple monitors, but now it sounds like it's only for fancy things. Is that right?

**Comment by falkTX** [comment]
yes, and since the plugin is embedded in another window multi-monitor support simply makes no sense.

**Comment by falkTX** [comment]
btw, before I forget.
if possible update to the distrho/juce repo again (the changes from ~9 days ago).
a serious lv2 bug was in there, that might cause the ui to crash when loaded (race condition).

**Comment by mtytel** [comment]
Removed the dependency in version 0.6.2
