### ISSUE TITLE
[LV2] Arpegiator does not sync in Ardour

### ISSUE THREAD

**Issue by rghvdberg** [mtytel/helm#63]
$ardour4 --version
    bind txt domain [gtk2_ardour4] to /opt/ardour4/share/locale
    Ardour4.4.143 (built using 4.4-143-g8ab69cb and GCC version 4.4.7)

    $ helm --version
    Helm 0.5.1

the vst version does a little better

**Comment by falkTX** [comment]
I did the lv2 code for juce, so I should be able to fix issues that are on the wrapper-side of things.
I'll make a note to test the lv2 time sync code again in ardour.

**Comment by mtytel** [comment]
I also haven't updated to the latest JUCE DISTRHO version in a while.. Not sure if that has anything to do with it.

**Comment by rghvdberg** [comment]
downloaded and installed 0.6.0
everything seems fine now :+1: 
closing this

**Comment by mtytel** [comment]
Sounds like @falkTX fixed this in his branch of JUCE. 
I'll update soon

**Comment by mtytel** [comment]
Updated to the version with falkTX's fix.
