### ISSUE TITLE
request: support multi-channel input with separate pitch-bend

### ISSUE THREAD

**Issue by wolftune** [mtytel/helm#64]
This is *the* major feature that allows synths like this to work with a wide manner of alternate-tuning softwares and controllers:

* Allow input on all 16 MIDI channels
* Keep all settings for the single Heml instance identical across channels (this is not about 16 different timbres!)
* Allow the pitch-bend signal from each channel to affect just that channel's output
* Ideally (not absolutely essential) allow a whole-instrument setting of pitch-bend range (+/- 1 is desireable in some cases, but +/- 2 is workable in some others)

Since range and 16-channel input all work already, the only thing missing is keeping the pitch-bend segregated to only act on those pitches that came from the same channel as the pitch-bend signal!

**Comment by wolftune** [comment]
I should mention that various tuning-table settings to set the pitch of every key, perhaps via sysex and such is also stuff that is nice, and for people not using other software for tuning, just having built-in tuning functions (as in ZynAddSubFX) is certainly nice, but it is both less flexible and far more work to implement than just this simple pitch-bend support.

**Comment by mtytel** [comment]
This is done in version 0.6.1
