### ISSUE TITLE
Helm does not output sound when re-opening a file in Logic

### ISSUE THREAD

**Issue by Shrinks99** [mtytel/helm#65]
Helm doesn't seem to actually output sound when a file is opened with helm synthesizers used as instruments.  The plugin can only be used when the channel is switched to a different software synthesizer and then set back to Helm as shown in [this video.](https://www.youtube.com/watch?v=IJTYqsheCvQ) (Apologies for the bad framerate.)

**Comment by genlog** [comment]
the video is private :-)

**Comment by Shrinks99** [comment]
>_<  https://www.youtube.com/watch?v=IJTYqsheCvQ fixed

**Comment by mtytel** [comment]
Hmmm. I haven't seen this behavior before.. Looking into it.

**Comment by mtytel** [comment]
I think this was fixed with issue #82
