### ISSUE TITLE
created patch lost after saving project.

### ISSUE THREAD

**Issue by genlog** [mtytel/helm#66]
Hi,

Yesterday i tried 0.6.1 (vst) on bitwig studio. I created a patch and saved the project.

After reopening the projected i noticed that the patch was lost. 
The parameters were different. The osc's, filter, etc didn't match anymore.
I save the patch also before in helm. I could open the patch in helm again.
I looks like only there parameters aren't correctly saved in the project.

The created patch:
![helm-created-patch](https://cloud.githubusercontent.com/assets/14365272/12295166/8d02d3ba-b9ff-11e5-8f29-a2d9568d4f2d.jpg)

Patch is lost

![helm-after](https://cloud.githubusercontent.com/assets/14365272/12295165/8cff8386-b9ff-11e5-924e-ce3c7d150cd4.jpg)

**Comment by mtytel** [comment]
Woah. Bizarre. I'll try and repro this. 
What OS are you on?

**Comment by kpanic** [comment]
same here, under linux & renoise (helm VST flavuour)
Awesome synth & UI btw, thank you! :)

**Comment by genlog** [comment]
i'm also on Debian linux and Bitwig 1.3.5

**Comment by mtytel** [comment]
Well I finally found (and fixed) this issue.
It's specific to the VST and only occurs in some DAWs. If you load a project back up in Bitwig, Helm correctly loads all the settings back but right after, Bitwig sends a program change for the last selected preset. Seems like the accepted solution is a timer hack, if the program change comes right after a load from state call, ignore it. Kind of ugly...

http://www.juce.com/forum/topic/problems-recalling-plugin-state-versus-current-preset
