### ISSUE TITLE
make tries to create /usr/share/helm before installing

### ISSUE THREAD

**Issue by suhr** [mtytel/helm#67]
It seriously should not.

Part of the compile log:
```
Linking HelmPlugin
Compiling juce_audio_utils.cpp
make[2]: Leaving directory '/var/tmp/portage/media-plugins/helm-0.6.0/work/helm-0.6.0/builds/linux/LV2'
./lv2_ttl_generator build/helm.so
Generate ttl data for 'build/helm.so', basename: 'helm'
 * ACCESS DENIED:  mkdir:        /usr/share/helm
Writing manifest.ttl... done!
Writing helm.ttl... done!
Writing presets.ttl...
Saving preset 1/2... done!
```

UPDATE: `make install` tries to create `/usr/share/helm/patches` outside DESTDIR.

**Comment by mtytel** [comment]
Ahhhhh interesting.. The lv2 preset generator Makefile actually launches the lv2 plugin. Then the plugin tries to put some patches in /usr/share/helm
I'll see what I can do.

**Comment by mtytel** [comment]
All done! in the development branch
