### ISSUE TITLE
No waveform display for sample and hold in LFO

### ISSUE THREAD

**Issue by rghvdberg** [mtytel/helm#69]
Linux - Helm 0.6.1(kxstudio package)
Windows 10 - Helm 0.6

No waveform display for sample and hold in LFO
![selectie_009](https://cloud.githubusercontent.com/assets/10710663/12372719/341abbaa-bc61-11e5-8f48-1f7d7995a56c.png)

**Comment by mtytel** [comment]
Yea wasn't sure what to put since it's random... Could do a waveform that looks random like other synths do.

**Comment by rghvdberg** [comment]
I thought so,  but it's confusing.

Do a blocky random wave and a smoothed one for the "with glide"
Op 24 jan. 2016 23:44 schreef "Matt Tytel" <notifications@github.com>:

**Comment by mtytel** [comment]
Done!
