### ISSUE TITLE
wishlist: 3rd envelope generator

### ISSUE THREAD

**Issue by suedwestlicht** [mtytel/helm#7]
To manipulate oscillators a 3rd envelope generator would be fine.

You should name them "ENVELOPE 1" to "ENVELOPE 3" or "EG1" to "EG3" since their assignments are variable. "AMPLITUDE ENVELOPE" and "FILTER ENVELOPE" are misleading as there is no static assignment.

**Comment by mtytel** [comment]
Yea I think a third one would be good. Not sure where I'll put it in to the UI.. I was thinking about making the third a more complicated, multi-stage envelope. One where you can add in points dynamically. Does that sound good or would a third normal envelope be fine for what you want?

The amplitude envelope and filter envelope are hard wired in though, are you not seeing that behavior?

**Comment by suedwestlicht** [comment]
I see, you're right. Of course they are hardwired, too.

I'd say that a 3rd EG could be a copy of the existing ones. How about naming it AUX ENVELOPE and putting it graphically between AMPLITUDE ENVELOPE and FILTER ENVELOPE? Three equally sized areas. I think it's no problem to make them 1/3 smaller.

I never needed an envelope more complicated than ADSR.

**Comment by mtytel** [comment]
Well this is finally done, had to restructure the UI a bit but it think it still looks good.
In development branch.

**Comment by suedwestlicht** [comment]
This looks very good. Thank you.
