### ISSUE TITLE
Unclear how to enable LFO

### ISSUE THREAD

**Issue by rpazyaquian** [mtytel/helm#72]
I'm having trouble understanding when and how an LFO is enabled. Switching through the presets, I see that sometimes the helm icon for an LFO has a green bottom:

![screen shot 2016-02-02 at 11 21 03 pm](https://cloud.githubusercontent.com/assets/5279463/12772869/d354378c-ca03-11e5-9482-444ffb1da69c.png)

but I haven't found what causes this to toggle. Is there a setting elsewhere outside the instrument editor?

**Comment by mtytel** [comment]
Yea, I need to make this more obvious.
What you do is click on the little helm icon next to a modulation source like an LFO. This creates an overlay on knobs you can modulate.
Then, click and drag on a knob with an overlay to send the LFO to control that knob/parameter.
You can double click on the overlay to remove the modulation.
Then click on the little helm icon again to hide the overlay, but the modulation should still show on the parameter.

Hope that helps, this will definitely go in the manual/quickstart guide when I make that.

**Comment by rpazyaquian** [comment]
Yes, I think I understand now. I started an FAQ page on the wiki that answers this question. I hope that's okay.
