### ISSUE TITLE
Distortion when lots of notes overlap

### ISSUE THREAD

**Issue by spectromas** [mtytel/helm#74]
I've noticed this with a few patches I've made so I simplified one to see where the problem lies, this is with just a sine wave without any modulation or effects. 
I've attached audio file and the patch in case that helps, as far as reproducing it just seems to be a case of having a fairly long amp envelope and sequencing fast notes. I saw #6 but I'm not sure if that is the same thing. 
This is in linux 64 bit with a latest git master build. 
Also, volume doesn't change the distortion.

[bug_distortion Sines.helm.zip](https://github.com/mtytel/helm/files/120817/bug_distortion.Sines.helm.zip)

**Comment by mtytel** [comment]
Alright, I finally looked at this. It's definitely an issue. 

What's happening is the audio is routed through a soft clipping before it is sent out through the volume control. So if the volume control is less than one then the notes will distort from the soft clipping at 0dB then get turned down by the volume control which results in distorted quiet output.

To "fix" this, I've increased the volume range past 1 and set the default to 1. That way, the notes by default will distort as they get really close to 0dB (where it would hard clip distort on audio output).

What I need to do is put a "Gain" control before the soft clipping along with a VU meter that turns red when distorting so people can control the distortion better.

Thanks for reporting this by the way. Sorry it took so long to look into. :/

**Comment by spectromas** [comment]
Thanks for explaining what the problem is and I'm glad you were able to reproduce it.

**Comment by mtytel** [comment]
I've removed the soft clipping for now, added a peak meter and added hard clipping at gains -2 to 2.
So when multiple notes overlap it won't distort until it gets above the hard clip gains which will tell you to bring down the volume.

This will be out in the next version.
Next step is to add back in the soft clipping as an option along with some other distortions.
