### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by danboid** [mtytel/helm#75]
I was hoping to try Helm out under Arch Linux on my Banana Pi. I realise its only got a (dual-core) 1 Ghz ARMv7 CPU so I think I'll be lucky to get more than a couple of instances of Helm running on it, if that. It'd be cool if I can just use 1 instance of Helm as then I could then potentially use it as a live instrument. A more realistic ARM platform would be something like one of the 64 bit AArch64 Nvidia Shield devices - they compete quite well with i3 machines I believe.

I can probably (hopefully) just hack the current makefiles to remove the sse2 flags but if Helm can't get ARM NEON support any time soon then it would be nice if it could detect non-x86 CPUs and disable sse2 and any other x86-specific automatically.

Thanks!

**Comment by mtytel** [comment]
Hmmmm... Yea I can look into this.
Do you know if JUCE compiles to ARM? I'm dependent on that framework so that would be a necessary first step.

**Comment by danboid** [comment]
Hi Matt!

That's great news!

Yes, JUCE builds fine under ARM. I've built JUCE and TAL-Noizemaker fine under ARM Linux.

Thanks!

**Comment by danboid** [comment]
I presume you don't have any (non-Android) ARM Linux boxes? I can highly recommend the Banana Pi but if you want something with more CPU horsepower there is the ODROID XU4 which is still very affordable but has a Octacore CPU, 2 GB RAM and USB 3.0 so it should offer better IO than the BPi and similar.

They're so much fun! :)

**Comment by danboid** [comment]
With any luck we'll be able to buy the pine64 board soon too, the low-end model of which promises to bring us a 64 bit ARM board for $15!

Hopefully they'll release a pine board with SATA or USB 3.0 for peanuts too? That's where the pine64 falls down for me but it'd prob be better for running helm than the BPi thanks to a superior CPU.

**Comment by mtytel** [comment]
I've got a Beaglebone black laying around somewhere. It's ARM and I think has a Debian based OS.
I'll try and get it working with that.

**Comment by danboid** [comment]
Cool!

Thanks Matt!

**Comment by danboid** [comment]
I have got Helm to build, install and run (just about) with qtractor under Arch Linux on my BPi. All I had to do was to remove every reference of sse2 from standalone/builds/linux/Makefile and helm.jucer.

It's not really usable though. Whenever I play a note with the  default patch, Helm/qtractor uses about 70% of my CPU and I get plenty of xruns.

Is there any hope for the Helm SSE code being accompanied by NEON code for ARM users? That may make it fast enough to run at least one instance well so the BPi, RPi 2 etc could be used as cheap, low-power Helm live instruments.

**Comment by pruperting** [comment]
Seconded. I managed to get Helm to compile on a Raspberry Pi 3 - but it segfaults on startup and doesn't say why (it initially errored due to no jack, but I fixed that).

Native Helm on the RPi would be cool for a project I am working on.

**Comment by dhilowitz** [comment]
I had the same experience on Raspberry Pi 2. I removed all the references to -msse2 and was able to get it to compile, but now I get a Segmentation Fault every time I run it.

**Comment by kjyv** [comment]
On my raspberry pi 3, I've replaced all the -msse2 occurences with -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard and I can run helm fine at least as lv2 plugin. For standalone, strace shows that it tries to open a connection to X11 (localhost:6000) and somehow fails on that. I've not used any GUI, but sound is mostly fine. It does have problems with some of the more cpu-heavy presets and some presets (e.g. CM FM Style) sound quite a bit different compared to the VST on my laptop. Not sure if the optimizations have any effect on that?

**Comment by kjyv** [comment]
For RPi 3 the whole line should be (the previous arguments are also ok for RPi2):
CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -fPIC -O2 $(DEBCXXFLAGS) -ffast-math -ftree-vectorize -march=armv8-a -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard

**Comment by mtytel** [comment]
Thanks for the research on this.
I'll look into the x11 issues. Not sure what's up with that.

As for the presets that sound different, are you building on the develop branch or master? I made some changes in develop that will make *some* settings sound different. 

If you're on master, it could be some of the ffast-math stuff.. Not sure though.

**Comment by mtytel** [comment]
I'll check out the CPU usage too. Maybe I'll put in a build flag that limits the polyphony..

**Comment by kjyv** [comment]
I'm using current git, yes. It seems for the FM Style that the filter envelope which is linked to the filter Env depth is not used (the sound does not have that wobble), but I can't really see that without the GUI atm. I've tried adding -fno-unsafe-math-optimizations (unsafe-math-operations is part of -ffast-math) which on ARM disables using the neon extensions that are not completely IEEE 754 compliant. That sounded exactly the same though, so I'd say it's not because of that. I've limited Polyphony already with the existing parameter but for some sounds even just playing one note is too much (only very few though). Also playing multiple notes in fast succession that use delay or reverb can cause too much load.

**Comment by mtytel** [comment]
Ok. I'll have to take a look at why it sounds different on an ARM machine because all the versions of Helm sound *mostly* the same on my x86 machines. I'll fire up my beaglebone..

The few patches that kill your pi are probably the ones with stutter enabled. It's not the most efficient effect..

**Comment by mtytel** [comment]
Just spent some time making the stutter more efficient and now it's actually pretty cheap.
That might get you some more polyphony.

**Comment by kjyv** [comment]
That sounds good, but stutter right now is only about 10% cpu. Reverb has 10-12%, Formant has 8-10%. I guess there are a few other things that make the sound crackle though (already at 70% cpu). Not sure how well it will run on your much slower beagle bone but I guess with a little tweaking Rpi 3 can be considered enough to play helm, maybe with higher latency settings, minimizing background processes or overclocking a little.

**Comment by mtytel** [comment]
Guess what I found in my closet? A Raspberry Pi 3 B that I forgot I had!
Getting it up and running...

**Comment by mtytel** [comment]
I'll probably try and get it working with raspbian because it's the most common?

**Comment by kjyv** [comment]
Ah, thats a nice thing to have lying around :) I'd recommend raspbian for support and ease of use

**Comment by dhilowitz** [comment]
Excited to hear how you make out!

**Comment by mtytel** [comment]
Alright I can get helm up and running in Debug.
I was super excited and built for Release but I crash anytime JUCE tries to call the standard library atomic::store (which is often).
I think this has to do with an atomic alignment bug in gcc4.9 so maybe upgrading to 5+ will fix that.

Ideally I could just get this building on launchpad.net.. Trying that now.

**Comment by kjyv** [comment]
Strange, I can run it fine in Release. How did you change the Makefiles?

**Comment by mtytel** [comment]
Instead of -msse2 I include the $(SIMDFLAGS) variable. Defined like this:

    ifeq ($(ARM), 1)
        SIMDFLAGS := -march=armv8-a -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -funsafe-math-optimizations
    else
        SIMDFLAGS := -msse2
    endif

**Comment by mtytel** [comment]
I changed it a bit to for launchpad. Apparently on aarch64 machines these flags are not defined because neon and hard floats are forced: -mfpu=neon-fp-armv8 -mfloat-abi=hard

Also just realized -funsafe-math-optimizations is redundant after -ffast-math

**Comment by mtytel** [comment]
You have gcc v4.9 on your PI?

**Comment by kjyv** [comment]
Ah, ok, I get the same crash at atomic_store when starting standalone when compiling with release. Lv2 works ok with Release.

**Comment by mtytel** [comment]
Got it working in Launchpad and the deb package works!
Haven't fully tested yet but it's working so far on the raspberry pi. Not sure why I get the crash when building on the raspberry pi though..

You can try it out here:
https://code.launchpad.net/~tytel/+archive/ubuntu/helm/+build/12824763/+files/helm_0.8.6-1335~ubuntu14.04.1_armhf.deb

**Comment by danboid** [comment]
Great to see progress being made on this this! I'll have to try it again on one of my ARM boards soon.

**Comment by mtytel** [comment]
Alright if you go to the site (http://tytel.org/helm) and download it should detect armhf and give you that version on Raspberry Pi. Working on adding it to the downloads list page.

**Comment by rbnpi** [comment]
Wonder if the passage of time and the advent of the Raspberry Pi4 makes this a goer now? Will it build there? Is there a suitable package already?

**Comment by mtytel** [comment]
If you download from the raspberry pi it should give you a build that works. Haven't tried on the pi4 tho.

**Comment by rbnpi** [comment]
Thanks. Found it, downloaded and working fine on my 4Gb Pi4

**Comment by aaaidan** [comment]
@rbnpi could you elaborate what “working fine” means for pi4? 😯

**Comment by rbnpi** [comment]
Well I just clicked on Download from the Helm website on Chromium on a Pi4 and it downloaded the .deb file automatically.
I have used it with the article on Helm control I wrote at https://rbnpi.wordpress.com/sonc-pi-helm-synth-toucdhosc-combined <https://rbnpi.wordpress.com/sonc-pi-helm-synth-toucdhosc-combined>
Although this is illustrated on a Mac it works fine on my Pi4, using my own build of Sonic Pi.
Of course you can just use it stand alone with a midi keyboard input to the Pi4 and audio out via the system audio.

**Comment by rbnpi** [comment]
Well I just clicked on Download from the Helm website on Chromium on a Pi4 and it downloaded the .deb file automatically.
I have used it with the article on Helm control I wrote at https://rbnpi.wordpress.com/sonic-pi-helm-synth-touchosc-combined <https://rbnrpi.wordpress.com/sonc-pi-helm-synth-touchosc-combined>
Although this is illustrated on a Mac it works fine on my Pi4, using my own build of Sonic Pi.
Of course you can just use it stand alone with a midi keyboard input to the Pi4 and audio out via the system audio.

**Comment by rbnpi** [comment]
Well I just clicked on Download from the Helm website on Chromium on a Pi4 and it downloaded the .deb file automatically.
I have used it with the article on Helm control I wrote at https://rbnrpi.wordpress.com/sonic-pi-helm-synth-touchosc-combined <https://rbnrpi.wordpress.com/sonic-pi-helm-synth-touchosc-combined>
Although this is illustrated on a Mac it works fine on my Pi4, using my own build of Sonic Pi.
Of course you can just use it stand alone with a midi keyboard input to the Pi4 and audio out via the system audio.

**Comment by aaaidan** [comment]
@rbnpi thanks! Given the pi3 barely has enough compute power to run helm, was wondering if you could weigh in on how it performs on pi4? Number of voices, buffer size, etc?

**Comment by rbnpi** [comment]
Just looked at it again on my Pi4. running as standalone, not embedded. On supplied settings works well (512 buffer). I've tried reducing this (just using built in audio which is not great: might be better with pisound audio board). OK on many voices with 128, but some break up on more complex ones. Cranked up the number of voices. Again it copes OK. Added a PiSound board: running happily with reduced buffer size, so your audio setup is the limiter here. On the processor front a Pi3 is fairly maxed out on the cpu usage monitor when helm is running.  Pi4 is not stressed at all (mine has 4Gb of RAM): bottom line, if you have a Pi4 its certainly worth a look with Helm eg just running Stinky bass 3 with 8 voices 256 byte buffer, 96000Hz 2.7ms latency into PiSound Board on Pi4. with midi keyboard driving it. No problem.

**Comment by aaaidan** [comment]
Thanks for this detailed info! Was on the fence about trying to build a teeny helm midi box, but it’s pretty clear it would work well enough to try! 🤖 @rbnpi

**Comment by rbnpi** [comment]
Let me know how you get on.

**Comment by bonjorno7** [comment]
This is a bit late but, there's no build for ARM available on the website. There's Linux 64 and 32 bits, but neither are for ARM. Unless I'm missing something?

**Comment by rbnpi** [comment]
Just download on your pi it sutomatolically chooses the correct”Linux” for it even though not listed.

**Comment by bonjorno7** [comment]
The website thinks my Pi 400 (the one built into a keyboard) is running i386 architecture.
Having the option to manually choose not only operating system but also architecture would be nice.
