### ISSUE TITLE
Speed up waveform display refresh rate

### ISSUE THREAD

**Issue by unfa** [mtytel/helm#78]
The Helm's waveform display is kind of laggy refreshing at about 15~20 FPS. Could it be bumped up to 30 FPS?

**Comment by mtytel** [comment]
Yea it can but for some reason JUCE uses a lot of processing to draw them so I dropped it down.
Maybe I'll increase it again if I can get the cpu usage down.

**Comment by mtytel** [comment]
I'm going to rework some of the graphics in Helm by doing Open GL stuff.
Should get 60fps after that transition.

**Comment by mtytel** [comment]
All done! It looks really good now.
It'll come out in the next version.
