### ISSUE TITLE
feature request: sync osc cross-mod

### ISSUE THREAD

**Issue by JurekRaben** [mtytel/helm#8]
Hey, would be very nice if there was also an OSC cross mod sync option available. Best would be sync, ring mod, sync+ring mod.

Thanks for considering!

**Comment by mtytel** [comment]
Yea I'll have to think about this. I like these features but it's super easy to put every feature under the sun in! I'll probably prioritize feature requests that add UI elements by popularity so if other people request this I'll more likely add it in. Thanks for requesting :)

**Comment by mtytel** [comment]
Trimming features that won't ever go into Helm.
Putting this on the list for a new synth in the works.
