### ISSUE TITLE
feature request: Paning based on note on a scale.

### ISSUE THREAD

**Issue by scj643** [mtytel/helm#80]
A way to have the synth pan based on the note being played just like a piano would be awesome.

**Comment by mtytel** [comment]
Yea I'm considering putting in some stereo options. I'll put this on the list.

**Comment by unfa** [comment]
If panning control for oscillators is introduced, the "Note" modulation source could be used to do just that.

**Comment by mtytel** [comment]
There's no stereo chain in Helm and I'm wrapping up the features in Helm so can't really implement this.
That said, my next synth has a full stereo chain (and parallelized with SIMD) and will have ways to pan each oscillator. Not sure when it's coming out though.
