### ISSUE TITLE
Breaking bug when loading projects with helm - loud noise, then sound stops working

### ISSUE THREAD

**Issue by bjporter** [mtytel/helm#82]
Hello @mtytel,

I found a breaking bug, where if I save the project in (Cubase 6 32bit, Win7 64bit), and reload it, there is a brief loud noise, then my audio interface stops working. Otherwise the synth seems to work ok from what I can tell. It's just unusable if i need to load a project.

I confirmed this doesn't happen with any other synths.

We're hoping to use Helm for the next One Synth Challenge (over at kvraudio).

**Comment by mtytel** [comment]
Whelp. Yea that's pretty bad.
I got a deadline now :|

**Comment by mtytel** [comment]
OK, I found the problem. Haven't started fixing yet but shouldn't be too bad.
If I send you a build when it's done could I have you verify the fix before I release it?

**Comment by bjporter** [comment]
Wow, awesome! Yeah absolutely. Send me the build

**Comment by mtytel** [comment]
OK I'm pretty sure I fixed this bug, could you test out the new build?
http://tytel.org/static/dist/Helm_64bit_v0_7_1.msi
Thanks!

**Comment by bjporter** [comment]
Works great! 

Amazing work you guys are doing. Lightning speed fixes :dancer:

**Comment by mtytel** [comment]
Awesome!
