### ISSUE TITLE
Midi learn is ignored when plugin window is closed

### ISSUE THREAD

**Issue by theKGS** [mtytel/helm#86]
This plugin works fine when running normally in cubase, but only when the Helm window is open. If I close the window, the plugin starts ignoring all midi learn data until I open the window again.

I have a bass synth with a filter controlled by modulation (CC1) and as soon as I close the window the filter stops moving until I open it again. Very annoying.

**Comment by mtytel** [comment]
Oh shoot that is annoying.
I think I beat you to the punch though and this bug is already fixed. 
Fix will be out in the next version that's coming out soon.
