### ISSUE TITLE
Feature request: 32 bit build for OSX

### ISSUE THREAD

**Issue by JurekRaben** [mtytel/helm#9]
Would be very nice if you would enable the 32 bit target in the Xcode options, too, since lot of musicians still use 32bit versions on OSX (including me) for compability reasons. 32bit->64bit bridges always slow down gui and processing. Thanks for considering it!

**Comment by mtytel** [comment]
Woah I didn't know any Macs had 32 bit builds anymore.
Yea I'll make a universal build. Next release should have it.

**Comment by mtytel** [comment]
This should work now in version 0.4.0 up on the site! tytel.org/helm
