### ISSUE TITLE
level matched presets

### ISSUE THREAD

**Issue by ssj71** [mtytel/helm#91]
I was demoing a lot of the presets for the open source musician podcast and found that some of the presets are VERY loud. No damaged equipment or ears or anything, but it is a good idea to either write a script that loads presets and adjusts their gain do do the tedious manual thing. Unfortunately it was too late at night for me to think of writing down which ones were too loud. Sorry.

Thanks. Really love this synth.

**Comment by mtytel** [comment]
Thanks!
Yea I actually went through them and leveled most of them right before you filed this bug. Not sure if you didn't get that build or if it's the fact that new versions of Helm don't delete the *old* patches so some of the factory patches that were moved still are unleveled.

**Comment by ssj71** [comment]
ah I'll bet its the latter because most (if not all) the presets had duplicates. I'll mention it next podcast so users know about that.

**Comment by mtytel** [comment]
This'll probably require another pass at some point but the worst was fixed.
