### ISSUE TITLE
feature request: Pulse Width for oscillators

### ISSUE THREAD

**Issue by avish** [mtytel/helm#92]
Can we have a modulatable control for pulse width on oscillators? Could apply only in square mode or a new pulse mode.

**Comment by mtytel** [comment]
The sub has a "shuffle" feature that is really similar to pulse width.
I'm trying to not add any features at the moment so I'll put this as a v2.0 feature.

**Comment by mtytel** [comment]
Trimming features that won't ever go into Helm.
Putting this on the list for a new synth in the works.
