### ISSUE TITLE
Microtonality support

### ISSUE THREAD

**Issue by suhr** [mtytel/helm#94]
See [MIDI Tuning Standard](http://www.microtonal-synthesis.com/MIDItuning.html) and [Scala file format](http://www.huygens-fokker.org/scala/scl_format.html).

Additional info: [31ET](http://31et.com/) is [fun](http://tinyurl.com/zwf4jm5).

**Comment by Omega9** [comment]
https://github.com/mtytel/helm/issues/87

**Comment by mtytel** [comment]
Closing as duplicate
