### ISSUE TITLE
Issue With Loading a Saved File in LMMS

### ISSUE THREAD

**Issue by BiRD4** [mtytel/helm#97]
After loading an already saved .mmpz file, any saved Helm presets look like they have been set to the initial preset, while still sounding like they have the settings they had when they were saved - whenever a setting is changed, it stops having the value it had and is set to whatever it is set to, as if the setting was in an initial preset in the first place.

I was using Windows 8.1 64-bit and LMMS version 1.1.3. I used VeSTige to open Helm.

**Comment by mtytel** [comment]
Again thanks, looking into it.

**Comment by mtytel** [comment]
Fixed in development branch.
