### ISSUE TITLE
MIDI-mapped parameter changes don't update visual display

### ISSUE THREAD

**Issue by avish** [mtytel/helm#99]
When changing parameters using MIDI-mapped controls, the visualized display doesn't change.
This is particularly evident on envelopes, where changing any of the A/D/S/R parameters via a MIDI mapped control updates the bar for that parameter, but doesn't redraw the envelope. The same happens when changing cutoff/resonance on the filter using a MIDI control: the horizontal/vertical bar changes, but the filter curve is not redrawn.

This makes it harder to use Helm with a MIDI controller because you lose the great visualizations that make Helm so easy to work with.

**Comment by BiRD4** [comment]
Same thing happens with the VST plugin controls in VeSTige. Forgot to report that issue. These are both probably just the same problem.

**Comment by mtytel** [comment]
Fixed in development branch
